### ISSUE TITLE
Expected installer type for Nvidia drivers in source URL?

### ISSUE THREAD

**Issue by PedroMD** [Azure/batch-shipyard#103]
I'm trying to test NV-series VMs, but I'm not sure which source url I should use. I've installed NVIDIA driver on these NV VMs before and I've always used a recipe like (for Ubuntu 16.04):

```
wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-ubuntu1604_8.0.61-1_amd64.deb
sudo dpkg -i cuda-repo-ubuntu1604_8.0.61-1_amd64.deb
sudo apt-get -y install software-properties-common
sudo apt-get update
sudo apt-get install cuda -y
```

In order to achieve such a thing, what type of URL is the script expecting? Is it expecting a local installation like 
`https://developer.nvidia.com/compute/cuda/8.0/Prod2/cluster_management/cuda_cluster_pkgs_8.0.61_ubuntu1604.tar-gz`? There are different type of installers here https://developer.nvidia.com/cuda-downloads , so what should I use?

I'm referring to this `source` property found in the `pool.json` file:

```
 "gpu": {
            "nvidia_driver": {
                "source": "<URL for nvidia driver for STANDARD_NV VMs>"
            }
        }
```

Thank you!

**Comment by alfpark** [comment]
Official drivers for NV have been made available. I will automate the install in the next release.
