### ISSUE TITLE
Add users earlier in the pool setup process

### ISSUE THREAD

**Issue by mkiernan** [Azure/batch-shipyard#105]
The step to add an admin user to the compute nodes in the batch pool occurs as a final step: 
convoy.batch:_add_admin_user_to_compute_node

Unfortunately what this means is that when your start task is failing for whatever reason, it makes it very time consuming to troubleshoot, as you first have to go to the batch account in the Azure portal, drill down to the pool and one of the nodes, and manually add an account so that you can login to go and look at the logs to see what is going on. Some of the logs do come back to the shipyard node, but that's not always enough to figure out what the problem is, and you still need to login. 

What I would suggest is that we add the admin user _before_ the start task initialization and that will make things  a lot easier. You might argue that it's safer not to give access to the node in case any admin actions interfere with the start task, but personally I'd rather take that risk and have the capability to access the node. 

So my ask is can we move these 2 steps before the task initialization:
1) convoy.batch:_add_admin_user_to_compute_node
2) convoy.batch:get_remote_login_settings

And perhaps add a warning message: 
warning: it is recommended not to access the nodes until the pool creation start tasks have finished. 

Alternatively you could trap any failing start task exits and run those two steps during failed task exits to make sure the admin user & IP are available to then go and troubleshoot if necessary.

**Comment by alfpark** [comment]
Unfortunately, that is not possible (due to how Batch controls the start up procedure). You can still issue `pool asu` after the start task fails. Then ssh with `pool ssh`.
