### ISSUE TITLE
caffe2?

### ISSUE THREAD

**Issue by sandys** [Azure/batch-shipyard#112]
hi guys,
could you possibly build support for caffe2 ? 
its kind of semi-official for some usecases to migrate from caffe to caffe2 

- https://github.com/caffe2/caffe2/issues/862  
- https://github.com/caffe2/caffe2/issues/274

It would be great to have a working caffe2 + gpu pool setup on azure batch

**Comment by alfpark** [comment]
@sandys Batch Shipyard should support caffe2 out of the box. What specifically is the ask here? A recipe? If so, that is in the backlog.

**Comment by sandys** [comment]
Hi Fred,
Thanks for replying. Yes a recipe is what we are looking for.

Thanks!
Regards
Sandeep

On 14-Aug-2017 20:00, "Fred Park" <notifications@github.com> wrote:

@sandys <https://github.com/sandys> Batch Shipyard should support caffe2
out of the box. What specifically is the ask here? A recipe? If so, that is
in the backlog.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Azure/batch-shipyard/issues/112#issuecomment-322206009>,
or mute the thread

**Comment by sandys** [comment]
thank you so much!
