### ISSUE TITLE
Error installing batch-shipyard site extension 2.9.0 in Azure Function

### ISSUE THREAD

**Issue by hieuhc** [Azure/batch-shipyard#113]
I could manage to install previous versions. When I tried to update batch-shipyard extension, there was an error with permission denied. I deleted the current extension and tried to install 2.9.0, there was this error:

`Failed to install Batch Shipyard - ExitCode: 1, Output: D:\Program Files (x86)\Git\cmd\git.exe D:\Program Files (x86)\Git\bin\git.exe Your branch is up-to-date with 'origin/master'. Already up-to-date. "git clone failed", Error: Access is denied. Already on 'master' fatal: destination path 'D:\home\batch-shipyard' already exists and is not an empty directory., Kudu.Core.Infrastructure.CommandLineException: Access is denied. Already on 'master' fatal: destination path 'D:\home\batch-shipyard' already exists and is not an empty directory. D:\home\SiteExtensions\batch-shipyard\install.cmd at Kudu.Core.Infrastructure.Executable.ExecuteInternal(ITracer tracer, Func`2 onWriteOutput, Func`2 onWriteError, Encoding encoding, String arguments, Object[] args) at Kudu.Core.Infrastructure.Executable.ExecuteWithProgressWriter(ILogger logger, ITracer tracer, String arguments, Object[] args) at Kudu.Core.SiteExtensions.SiteExtensionManager.<>c__DisplayClass26_1.b__1() at Kudu.Core.Infrastructure.OperationManager.<>c__DisplayClass2_0.b__0() at Kudu.Core.Infrastructure.OperationManager.Attempt[T](Func`1 action, Int32 retries, Int32 delayBeforeRetry, Func`2 shouldRetry) at Kudu.Core.Infrastructure.OperationManager.Attempt(Action action, Int32 retries, Int32 delayBeforeRetry) at Kudu.Core.SiteExtensions.SiteExtensionManager.d__26.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) at Kudu.Core.SiteExtensions.SiteExtensionManager.d__25.MoveNext()`

**Comment by alfpark** [comment]
It looks like the site extension no longer invokes uninstall.cmd to upgrade. Will need to fix the install logic.

**Comment by alfpark** [comment]
This should be fixed. You can try to re-install Batch Shipyard **2.9.2** or later site extension on top of the failed one. If that doesn't work, I suggest opening up Kudu, going to a CMD shell and deleting the `%HOME%\batch-shipyard` directory (save any pertinent files like configurations that you may have placed there first).

**Comment by alfpark** [comment]
@hieuhc Please feel free to close the issue if the latest release has solved your problem. Thanks for reporting the issue.

**Comment by hieuhc** [comment]
I used Kudu to delete `batch-shipyard` directory in home folder, then re-installed Batch Shipard 2.9.2 site extension. And it was this error:

`Traceback (most recent call last): File "D:\home\Python35\lib\site-packages\pip\basecommand.py", line 215, in main status = self.run(options, args) File "D:\home\Python35\lib\site-packages\pip\commands\install.py", line 342, in run prefix=options.prefix_path, File "D:\home\Python35\lib\site-packages\pip\req\req_set.py", line 784, in install **kwargs File "D:\home\Python35\lib\site-packages\pip\req\req_install.py", line 851, in install self.move_wheel_files(self.source_dir, root=root, prefix=prefix) File "D:\home\Python35\lib\site-packages\pip\req\req_install.py", line 1064, in move_wheel_files isolated=self.isolated, File "D:\home\Python35\lib\site-packages\pip\wheel.py", line 345, in move_wheel_files clobber(source, lib_dir, True) File "D:\home\Python35\lib\site-packages\pip\wheel.py", line 323, in clobber shutil.copyfile(srcfile, destfile) File "D:\Python35_x64\Lib\shutil.py", line 115, in copyfile PermissionError: [Errno 13] Permission denied: 'D:\\home\\Python35\\Lib\\site-packages\\cryptography\\hazmat\\bindings\\_constant_time.pyd', Kudu.Core.Infrastructure.CommandLineException: Access is denied. HEAD is now at 9d66d75... Tag for 2.9.2 release Ignoring pathlib2: markers 'python_version < "3.5"' don't match your environment Ignoring scandir: markers 'python_version < "3.5"' don't match your environment Exception: Traceback (most recent call last): File "D:\home\Python35\lib\site-packages\pip\basecommand.py", line 215, in main status = self.run(options, args) File "D:\home\Python35\lib\site-packages\pip\commands\install.py", line 342, in run prefix=options.prefix_path, File "D:\home\Python35\lib\site-packages\pip\req\req_set.py", line 784, in install **kwargs File "D:\home\Python35\lib\site-packages\pip\req\req_install.py", line 851, in install self.move_wheel_files(self.source_dir, root=root, prefix=prefix) File "D:\home\Python35\lib\site-packages\pip\req\req_install.py", line 1064, in move_wheel_files isolated=self.isolated, File "D:\home\Python35\lib\site-packages\pip\wheel.py", line 345, in move_wheel_files clobber(source, lib_dir, True) File "D:\home\Python35\lib\site-packages\pip\wheel.py", line 323, in clobber shutil.copyfile(srcfile, destfile) File "D:\Python35_x64\Lib\shutil.py", line 115, in copyfile PermissionError: [Errno 13] Permission denied: 'D:\\home\\Python35\\Lib\\site-packages\\cryptography\\hazmat\\bindings\\_constant_time.pyd' D:\home\SiteExtensions\batch-shipyard\install.cmd at Kudu.Core.Infrastructure.Executable.ExecuteInternal(ITracer tracer, Func`2 onWriteOutput, Func`2 onWriteError, Encoding encoding, String arguments, Object[] args) at Kudu.Core.Infrastructure.Executable.ExecuteWithProgressWriter(ILogger logger, ITracer tracer, String arguments, Object[] args) at Kudu.Core.SiteExtensions.SiteExtensionManager.<>c__DisplayClass26_1.b__1() at Kudu.Core.Infrastructure.OperationManager.<>c__DisplayClass2_0.b__0() at Kudu.Core.Infrastructure.OperationManager.Attempt[T](Func`1 action, Int32 retries, Int32 delayBeforeRetry, Func`2 shouldRetry) at Kudu.Core.Infrastructure.OperationManager.Attempt(Action action, Int32 retries, Int32 delayBeforeRetry) at Kudu.Core.SiteExtensions.SiteExtensionManager.d__26.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) at Kudu.Core.SiteExtensions.SiteExtensionManager.d__25.MoveNext()`

I also tried go to `%HOME%\batch-shipyard` directory and installed from source, same error.

**Comment by alfpark** [comment]
It looks like some files are in use:

```
File "D:\Python35_x64\Lib\shutil.py", line 115, in copyfile
PermissionError: [Errno 13] Permission denied: 'D:\\home\\Python35\\Lib\\site-packages\\cryptography\\hazmat\\bindings\\_constant_time.pyd'
```

Try temporarily disabling your Azure Function, restarting your site, then attempt to install the site extension.

**Comment by hieuhc** [comment]
After stop the function, I could install Batch Shipyard 2.9.0 site extension successfully. Thanks for helping.
