### ISSUE TITLE
Can't deploy STANDARD_D16_V3 ?

### ISSUE THREAD

**Issue by PedroMD** [Azure/batch-shipyard#114]
Hello all,

I'm always getting a `The value provided for one of the properties in the request body is invalid.` error message. I did make sure the VM type was available on this location (WEST EU).

`STANDARD_D16` does not work either.

Is this an API issue?

**Comment by PedroMD** [comment]
Is it somehow related to https://github.com/Azure/batch-shipyard/issues/53 ?

**Comment by alfpark** [comment]
`Dv3` and `Ev3` sizes are not yet supported in Azure Batch (`STANDARD_D16` is invalid), but support is forthcoming soon. Please use `Dv2` sizes in the meantime, if possible.

**Comment by PedroMD** [comment]
Sorry for the late reply, @alfpark. Thank you - I will wait for it, then. Currently using `F16`, but I'm very interested in these `D_V3`... 

Is there any way I can be alerted of such availability?

**Comment by alfpark** [comment]
Typically, Azure Batch will offer VM Size availability as soon as a new size is offered on Azure. Unfortunately, it is taking longer than expected to roll out support for `Dv3` and `Ev3`. I will update this issue as soon as they are made available.

**Comment by PedroMD** [comment]
Great. Thank you.

Em 11/09/2017 4:58 da tarde, "Fred Park" <notifications@github.com>
escreveu:

**Comment by alfpark** [comment]
`Dv3` and `Ev3` should now be deployable in regions where this size is available.
