### ISSUE TITLE
pool udi for low priority nodes with ssh asks for password

### ISSUE THREAD

**Issue by hieuhc** [Azure/batch-shipyard#116]
I specified `ssh_public_key` and `ssh_private_key` in `pool.json`.  When running `pool udi` to update docker image for low priority nodes, it keeps asking for password. I thought it might be passphrase when generating ssh keys, so I  entered the passphrase (which is empty in my case so I just pressed Enter). After the second attempt the process is hung without any further warning.

**Comment by alfpark** [comment]
Did you add the pool ssh user prior to invoking `pool udi`? This is either done automatically for you if you added the ssh section before invoking `pool add` or manually via `pool asu`.

**Comment by hieuhc** [comment]
Yes I think I did. A ssh user is added in `pool.json` following [this instruction](https://github.com/Azure/batch-shipyard/blob/master/docs/13-batch-shipyard-configuration-pool.md) before invoking `pool add` to create a new pool. Although I find no message indicating that ssh keys are added successfully or not when `pool add` finishes.

**Comment by hieuhc** [comment]
I found the reason. After using `pool asu` to manually add ssh key then `pool ssh` to access one node in the pool, there is an error `ssh permissions are too open`. Changing permission of my private key fixes the problem.

But still, it would be nice if there is some notice message showing whether ssh keys are added to the pool with `pool add` successfully, and some warning message if the key doesn't work from `pool udi`.

**Comment by alfpark** [comment]
@hieuhc `pool add` and `pool asu` should both let you know when an SSH user is added (there will be diagnostic messages saying that remote users are being added to each compute node).

I can see if I can do a simple file mode check on the private key - but performing all possible checks for SSH compliance is out of scope.
