### ISSUE TITLE
Unused reference to the azure-mgmt package in convoy/keyvault.py?

### ISSUE THREAD

**Issue by lediur** [Azure/batch-shipyard#12]
I just tried running the Docker container version of the CLI, and I run into this error:

```
> docker run --rm -it alfpark/batch-shipyard:cli-latest
Traceback (most recent call last):
  File "/opt/batch-shipyard/shipyard.py", line 42, in <module>
    import convoy.fleet
  File "/opt/batch-shipyard/convoy/fleet.py", line 52, in <module>
    from . import keyvault
  File "/opt/batch-shipyard/convoy/keyvault.py", line 40, in <module>
    import azure.mgmt.resource.resources
ImportError: No module named 'azure.mgmt'
```

Seems like this import is unused? [`convoy/keyvault.py`](https://github.com/Azure/batch-shipyard/blob/master/convoy/keyvault.py#L40) I'll try removing that line and building the container on my end, and see if it breaks or not. edit: seems like it works

**Comment by alfpark** [comment]
@lediur Thanks for reporting this. You're correct, this should not have been imported. I'll include this fix in the next release.
