### ISSUE TITLE
Start task failed on every nodes when the pool auto-scales

### ISSUE THREAD

**Issue by hieuhc** [Azure/batch-shipyard#128]
I created a pool of `STANDARD_NC6` nodes with `pool add`. There is also an auto-scaling formula in pool.json. It has been working fine for a while. But suddenly after few weeks, when it scales, all the additional nodes are failed on start tasks, except for the base node (which is a low-priority node). When I delete and re-create the pool, it works again. 

This behavior repeats every few weeks. I wonder if you know what might be the reason for this? Thanks.

**Comment by hieuhc** [comment]
I attach here stdout.txt and stderr.txt from one of failed nodes. Looks like something with loading NVIDIA modules.

[stdout.txt](https://github.com/Azure/batch-shipyard/files/1344509/stdout.txt)
[stderr.txt](https://github.com/Azure/batch-shipyard/files/1344510/stderr.txt)

**Comment by alfpark** [comment]
What version are you using?

**Comment by hieuhc** [comment]
You are correct that I have been not using version `2.9.5`. It is also difficult to reproduce this error with current version I am using, except for waiting randomly for days/weeks. The newest version might have fixed the error as described in ChangeLog with "NV driver updates" and/or "OS updates and Docker issues". I updated to `2.9.5` and will let you know here if it happens again.Thanks for your feedback.
