### ISSUE TITLE
Tasks fail with exit code 125 when task specification is too long

### ISSUE THREAD

**Issue by hieuhc** [Azure/batch-shipyard#129]
Hi. This behavior usually happens when I submit a task with lots of environment variables inside. The task fails and produces this error. Seems like it hasn't pulled the docker image yet.

`docker: bufio.Scanner: token too long`

Can we have somewhere a number which is the maximum number tokens a task should contain?

**Comment by alfpark** [comment]
This appears to be a Docker limitation/bug rather than that of a Batch task. Batch Shipyard converts your env vars specified in your jobs configuration file into an env-file.

If you crack open the .envfile for your task, are there any lines that exceed 64K characters?

**Comment by hieuhc** [comment]
Ah I can see that the command invoked to run the task uses `--env-file` parameter of `docker run`. There is a resource file generated along with the task, its format is `*.envlist`. It contains all environment variables for the task. It size exceeds 64KiB, 104KiB to be exact. Maybe it exceeds the node's buffer size?

**Comment by alfpark** [comment]
This is a go/Docker issue, if I am interpreting my reading correctly.

If you have static environment variables, perhaps you can refactor those out into a resource file (or somehow read those separately) and source it as part of your command invocation.

**Comment by hieuhc** [comment]
Yes my thought is also this issue is from Docker. I probably should raise this issue to them. I will find a way to work around this. Thanks for your feedback.
