### ISSUE TITLE
Documented states appear to be swapped

### ISSUE THREAD

**Issue by jongiddy** [Azure/batch-shipyard#136]
I am confused by the text in parentheses at https://github.com/Azure/batch-shipyard/blame/75157e91f61ee36578107f9aed44e6d590435334/docs/30-batch-shipyard-autoscale.md#L41-L44 which associates "pending" with "active + running" and "active" with "queued".

It seems like it should be the other way around, e.g:
```
* `pending_tasks` will autoscale the pool using metrics for the number of
pending (i.e. queued) tasks for the pool.
* `active_tasks` will autoscale the pool using metrics for the number of
active (i.e. running) tasks for the pool.
```

Edit: From https://docs.microsoft.com/en-us/azure/batch/batch-get-task-counts it seems that the terminology is:
```
active (waiting to run) -> running -> completed
```

So, maybe the current description makes sense, although is still confusing. At the least, it would improve it to use the same terms within the parentheses:
```
* `active_tasks` will autoscale the pool using metrics for the number of
active (i.e. queued) tasks for the pool.
* `pending_tasks` will autoscale the pool using metrics for the number of
pending (i.e. queued + running) tasks for the pool.
```

**Comment by jongiddy** [comment]
Also, the asterisks used as bullet points here and further down should be replaced by dashes, to format correctly. See http://batch-shipyard.readthedocs.io/en/latest/30-batch-shipyard-autoscale/ where, rather than displaying as bullet points, the asterisk-bulleted lines alternate between italics and normal.

**Comment by alfpark** [comment]
The documentation is correct. I can add clarification - these scenarios refer to task states as they are assigned in the batch system.

* `active_tasks` should be interpreted as "tasks with satisfied dependencies awaiting node assignment".
* `pending_tasks` should be interpreted as "tasks pending completion"; this include active tasks as per above and any running tasks.

The correlation for these scenario names come from the [Autoscale formula variables](https://docs.microsoft.com/en-us/azure/batch/batch-automatic-scaling).
