### ISSUE TITLE
Allow autoscale to start nodes immediately

### ISSUE THREAD

**Issue by jongiddy** [Azure/batch-shipyard#138]
In the autoscale scripts, when a pool starts, the autoscale evaluation used for `active_tasks` or `pending_tasks` fails with the message 
```
Autoscale evaluation failed due to insufficient sample data
Line 9, Col 43: Insufficient data from data set: $PendingTasks wanted 70%, received 0%
```
due to the `GetSample(sli)` failing in lines like https://github.com/Azure/batch-shipyard/blob/75157e91f61ee36578107f9aed44e6d590435334/convoy/autoscale.py#L73

This causes both the `$TargetDedicatedNodes` and `$TargetLowPriorityNodes` to remain at 0 until the sample interval can be met.

Adding a conditional at this point allows it to start the minimum nodes immediately:
```py
'samplevecavg = samplepercent < {} ? max(0, lastsample) : avg(${}Tasks.GetSample(sli))'.format(pool.autoscale.scenario.required_sample_percentage, task_type),
```

**Comment by alfpark** [comment]
Great catch, thanks - will fix for the next release.
