### ISSUE TITLE
Autoscale algorithms don't take account of minimum node count

### ISSUE THREAD

**Issue by jongiddy** [Azure/batch-shipyard#139]
Thanks for your response to earlier issues.

The autoscale algorithms don't take account of minimum values for the less-favored node type.

If the `vm_count` stanza is set to:
```
        "vm_count": {
            "dedicated": 0,
            "low_priority": 1
        },
```
and one job is added, the `active_tasks` and `pending_tasks` algorithms will both set a dedicated node target = 1, even though a low-priority node should be running.

It appears that this would always be the case if the `vm_count` is not the same for both node types.

**Comment by alfpark** [comment]
The default mechanism is to equal weight (`bias_node_type`) option. I think if this option is set to `low_priority` then it should not allocate the additional dedicated node. However, this is a sub-optimal solution to the general case.

The current node counts need to be weighted into the equation (it's not being currently done outside of rebalance with preemption).

**Comment by alfpark** [comment]
If you can deploy using the `develop-cli` Docker image, please let me know if this fixes your issue.

**Comment by alfpark** [comment]
Closing, please re-open if you still observe this behavior in 3.0.0b1 or later releases.
