### ISSUE TITLE
Enhanced Singularity Support

### ISSUE THREAD

**Issue by alfpark** [Azure/batch-shipyard#146]
Enhance Singularity support. Continuing feature expansion from [initial support](https://github.com/Azure/batch-shipyard/issues/135).

- [x] Migrate to support Singularity 3 (targeting 3.3.0)
  - [x] Break cascade into Docker-specific and Singularity-specific paths
- [x] Support SIF ORAS-based images in ACR
- [x] Augment `pool images list` to support Singularity images (where the container runtime is installed)
- [x] Improve MPI mechanics (#287)
- [x] Update README and docs

Lower-priority work:
- [x] Image auto-verification support?
- [ ] Debian host OS support

**Comment by JonShelley** [comment]
Any update on when this capability is targeted for delivery?

**Comment by alfpark** [comment]
This workitem will be delayed until after Singularity 3.x is released. Fixes to the current Singularity support will continue in the meantime.

**Comment by ArangoGutierrez** [comment]
Heya any updates on this work item? singularity has already 3.1 and 3.2 releases and a Sylabs supported 3.1 release.

I would be happy to help on this work item.

I Volunteer :)

**Comment by alfpark** [comment]
Thanks for offering to help - this item will be delayed a bit further as some alignment takes place.

**Comment by alfpark** [comment]
Work is scoped and started.

cc @vincentlabonte
