### ISSUE TITLE
Support for recurring jobs and accessing credentials from containers

### ISSUE THREAD

**Issue by lediur** [Azure/batch-shipyard#15]
Is there a recommended way to use batch-shipyard with the Azure Batch job scheduler? I'd like to be able to schedule Docker jobs to run at a recurring interval, and I couldn't find documentation on this topic.

Also, I was wondering if there was a way to expose credentials to the running Docker container without saving them as variables in `jobs.json`? I'd like to provide some credentials for external services to the container, but I don't want to check these into source control. Using KeyVault from inside the container would also work, but I don't think those env vars are passed to the pool.

(p.s. is this the right place to ask questions about batch-shipyard usage, or is there a more appropriate forum for this?)

**Comment by alfpark** [comment]
@lediur Can you expand on your recurring job scenario? Do you need to execute more than one task for the job per recurrence? I think I can add support for 1 task per job per recurrence without too much new complexity.

Regarding credentials, right now, no. You would need to wrap the CLI in your own script to generate the json file temporarily to insert the credentials. I'd like to understand your scenario more here. At some point the credentials need to be exposed to Batch Shipyard. For example, a storage account key or KeyVault credentials which would then need to funnel through to the compute nodes running the containers. How are these creds input or read by the CLI? Perhaps a solution is to provide a keyvault secret id that contains env vars (a dictionary) which would be automatically populated by Batch Shipyard if a secret id env var property is specified in either the pool (for additional node prep) or the jobs json.

Opening an issue is ok to ask questions.

**Comment by lediur** [comment]
Thanks for your response! I would be using recurring jobs to run quite a few tasks per job. For example, let's say I have 10 cameras `cama1` through `camb5` that all write to an external server with file structure `date/cama1/cama1_date.mp4`. I want to do some processing that requires all of the videos for the same date and stores that up to blob storage. I also want to archive the raw footage in blob storage for later processing using a similar folder structure.

I thought I would write a job that has many fetch tasks, and then one processing task that depends on all of the fetch tasks. I could throw together a script to generate a jobs.json file and then run `batch-shipyard` using it (which is what I've done so far), but then I would have to find another way to schedule that script to run every day. This seems like my best bet without having to go through the complexity of speccing out another JSON format to define recurrences.

For credentials, using the same example as above: I have a username and password for the external that I'd like to pass to each of my fetch scripts, either as an environment variable or part of the command. Right now, I've just hardcoded the username and password into the `jobs.json` as a job-level environment variable, but that's not as secure as I'd like it to be. I'm using KeyVault secret ids with my `batch-shipyard` credentials.json by providing the directory_id, application_id, and aad_auth_key as environment variables. Storing environment variables as a secret id which is then fed to each node for jobs or tasks sounds like it would solve this problem nicely.

**Comment by alfpark** [comment]
More than 1 task per job for a recurrence will require a job manager to spawn and monitor each of the tasks to completion. Unfortunately, this will require quite a bit of work. I'll create an issue for this and add it to the 3.0.0 milestone (which won't be imminent for some time). You might be able to accomplish this yourself by creating a Docker image that packages the CLI + your script generator, then add that to the pool. Then you'll need to use the Batch API directly to create a recurring job using this image which would then add tasks to itself (i.e., it's own job). Unfortunately, you'd have to manage credential passing.

I think I can add secret_id support for env vars somewhat easily. However, encrypting these to hide for UI purposes might be a little tougher. I'll see if I can roll this into the next release.
