### ISSUE TITLE
Docker container updates for job

### ISSUE THREAD

**Issue by jcramer** [Azure/batch-shipyard#156]
What is the easiest way to get the docker container image to update for tasks when I've made a change to the image on dockerhub?  I've tried setting `remove_container_after_exit: true` in the jobs.yaml file but that didn't seem to do it.

I know that I can ssh into the VM and do a docker pull manually, I was just hoping there was a config flag that would take care of this for me.

**Comment by alfpark** [comment]
You can manually do this by running: `shipyard pool images update`

There isn't a way to make a job/task pull a newer image before execution. That's something that can be considered for improvement.

Also, resizing a pool (either manually or via autoscale) will always result in retrieving the latest image.

**Comment by jcramer** [comment]
ok thanks for confirming!  Good work on all of this, I've been using for a couple days now and works nicely so far.
