### ISSUE TITLE
New version of gluster uses glusterd.service instead of glusterfs-server.service

### ISSUE THREAD

**Issue by anhvoms** [Azure/batch-shipyard#161]
The setup script for gluster ran into some issue because it tried to start glusterfs-server and checking for the status of that systemd unit. It should check the version of gluster to determine which gluster service to check for. 

https://github.com/gluster/glusterfs-debian/issues/9

**Comment by alfpark** [comment]
Thanks Anh for reporting. I'll take a look at this and fix.

**Comment by alfpark** [comment]
I'll leave this open until 18.04. I'll migrate the RemoteFS clusters to use Bionic and then fix the scripts to work correctly with the renamed units.
