### ISSUE TITLE
Windows Pool Creation Error Downloading blobxfer

### ISSUE THREAD

**Issue by BenKoth** [Azure/batch-shipyard#171]
Creating a pool in windows I get the following error on the latest Development branch:

> Traceback (most recent call last):
>   File "G:\batch-shipyard\batch-shipyard\shipyard.py", line 1900, in <module>
>     cli()
>   File "G:\batch-shipyard\batch-shipyard\shipyard.venv\lib\site-packages\click\core.py", line 722, in __call__
>     return self.main(*args, **kwargs)
>   File "G:\batch-shipyard\batch-shipyard\shipyard.venv\lib\site-packages\click\core.py", line 697, in main
>     rv = self.invoke(ctx)
>   File "G:\batch-shipyard\batch-shipyard\shipyard.venv\lib\site-packages\click\core.py", line 1066, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "G:\batch-shipyard\batch-shipyard\shipyard.venv\lib\site-packages\click\core.py", line 1066, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "G:\batch-shipyard\batch-shipyard\shipyard.venv\lib\site-packages\click\core.py", line 895, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "G:\batch-shipyard\batch-shipyard\shipyard.venv\lib\site-packages\click\core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "G:\batch-shipyard\batch-shipyard\shipyard.venv\lib\site-packages\click\decorators.py", line 64, in new_func
>     return ctx.invoke(f, obj, *args[1:], **kwargs)
>   File "G:\batch-shipyard\batch-shipyard\shipyard.venv\lib\site-packages\click\core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "G:\batch-shipyard\batch-shipyard\shipyard.py", line 1189, in pool_add
>     ctx.table_client, ctx.config)
>   File "G:\batch-shipyard\batch-shipyard\convoy\fleet.py", line 2689, in action_pool_add
>     batch_client, blob_client, config
>   File "G:\batch-shipyard\batch-shipyard\convoy\fleet.py", line 1422, in _add_pool
>     nodes = batch.create_pool(batch_client, config, pool)
>   File "G:\batch-shipyard\batch-shipyard\convoy\batch.py", line 694, in create_pool
>     return wait_for_pool_ready(batch_client, config, pool.id)
>   File "G:\batch-shipyard\batch-shipyard\convoy\batch.py", line 634, in wait_for_pool_ready
>     settings.pool_settings(config).reboot_on_start_task_failed)
>   File "G:\batch-shipyard\batch-shipyard\convoy\batch.py", line 505, in _block_for_nodes_ready
>     'prior to the resize operation.').format(pool.id))
> RuntimeError: Please inspect both the node status above and files found within the safeguardtest/<nodes>/startup directory (in the
> current working directory) if available. If this error appears non-transient, please submit an issue on GitHub, if not you can dele
> te these nodes with "pool nodes del --all-start-task-failed" first prior to the resize operation.

In the stderr.txt:

> Invoke-WebRequest : The request was aborted: Could not create SSL/TLS secure channel.
> At D:\batch\tasks\startup\wd\shipyard_nodeprep_nativedocker.ps1:55 char:1
> + Invoke-WebRequest -Uri $bxurl -OutFile $bxoutf
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc 
>    eption
>     + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
>  
> D:\batch\tasks\startup\wd\shipyard_nodeprep_nativedocker.ps1 : Download from 
> https://github.com/Azure/blobxfer/releases/download/1.1.1/blobxfer-1.1.1-win-amd64.exe to 
> D:\batch\tasks\startup\wd\blobxfer.exe failed
> At line:1 char:1
> + shipyard_nodeprep_nativedocker.ps1 -v 3.2.0 -x 1.1.1
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
>     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,shipyard_nodeprep_nativedocker.ps1

stdout.txt

> Configuration [Native Docker, Windows]:
> ---------------------------------------
> Batch Shipyard version: 3.2.0
> Blobxfer version: 1.1.1
> Mounts path: D:\batch\tasks\mounts
> Encrypted: 
> Azure File: False
> 
> Docker version 17.06.2-ee-6, build e75fdb8
> Downloading blobxfer 1.1.1 binary as D:\batch\tasks\startup\wd\blobxfer.exe
> 

I'm not sure what would have changed, I didn't see anything in the script history but if I add the following before the Invoke-WebRequest in shipyard_nodeprep_nativedocker.ps1 it works.

```
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
Invoke-WebRequest -Uri $bxurl -OutFile $bxoutf
```

**Comment by alfpark** [comment]
Which `platform_image` are you using?

**Comment by BenKoth** [comment]
vm_configuration:
    platform_image:
      offer: WindowsServer
      publisher: MicrosoftWindowsServer
      sku: 2016-Datacenter-with-Containers

**Comment by alfpark** [comment]
Thanks - looks like there may have been a switch on github's downloads that only enable TLS v1.2. I believe powershell defaults to 1.0.

**Comment by alfpark** [comment]
Confirming, blog post: https://githubengineering.com/crypto-removal-notice/
