### ISSUE TITLE
Support "depends_on" in task_factory

### ISSUE THREAD

**Issue by whataride** [Azure/batch-shipyard#173]
Right now one cannot specify dependency of tasks generated by task_factory on other tasks. For example, I have a split task, which will split a file to smaller ones, and want to generate tasks to process each of the files created in the split task. This type of dependency is fairly common in jobs that requires map and reduce.

**Comment by alfpark** [comment]
Just to clarify, you want `depends_on` (or `depends_on_range`) within the each task specification to apply to the tasks generated by `task_factory`?

**Comment by whataride** [comment]
Yes, what we need is that each task specification generated from task_factory can depend on some other task.

To be more specific, here is an example:

`job_specifications:
- id: some-job
  tasks:
  - id: split_file
    output_data:
      azure_storage:
      - storage_account_settings: mystorageaccount
        remote_path: engressed-files
        local_path: $AZ_BATCH_TASK_WORKING_DIR
        include:
        - 'chunks/x*'
        blobxfer_extra_options: null
    command: mkdir -p chunks && split -n l/10 -d ./test/urls.txt && mv x* chunks
  - id: null
    # depends_on doesn't work for task_factory
    # depends_on:
    # - split_file
    task_factory:
      file:
        azure_storage:
          storage_account_settings: mystorageaccount
          remote_path: engressed-files
          is_file_share: false
          include:
          - 'chunks/x*'
        task_filepath: file_name
    command: cp {file_name} {file_name}_copied
`
Do we have a workaround for this kind of dependency right now?

**Comment by alfpark** [comment]
Ok, thanks. Because task factory tasks are not explicitly assigned task ids, this fails with the existing check. I can add an exception for these types of tasks. There is no current workaround.

I'll add support for this shortly in `develop` where you can test to see if this meets your needs.

**Comment by whataride** [comment]
Many thanks for the quick action! Really appreciated!

When will the change make to the stable version?

**Comment by alfpark** [comment]
Did this change work for you?

I hope to have `3.3.1` out within a week or so. There are a few minor additions slated.

**Comment by whataride** [comment]
I haven't tried it yet, but I will let you know once I do it. Thanks again!

**Comment by veonua** [comment]
does it work? as far as I understand batch-shipyard estimates tasks before chunks created, so I'm having 0 tasks from the factory
