### ISSUE TITLE
Where to find docker logs?

### ISSUE THREAD

**Issue by hildeweerts** [Azure/batch-shipyard#175]
Hi,

How I can retrieve the logs one would usually obtain using `docker logs CONTAINERNAME`, when using batch-shipyard? I am not sure whether this is the right place to ask this question, but I cannot seem to find the answer anywhere in the documentation.

Thanks!

**Comment by hildeweerts** [comment]
Thanks you so much for the quick response!

**Comment by sebastiankochman** [comment]
How can I find stdout.txt / stderr.txt on nodes that have been removed via autoscale feature? Is there some simple configuration that would upload these files e.g. to Azure Storage for analysis later?

**Comment by alfpark** [comment]
Files generated by tasks only exist while the compute node exists, unless you use a persistence mechanism. There are a few you can use:

1. `output_data` on the task
2. Mounting a volume defined in the global configuration `shared_data_volumes`. You can use `azurefile` or `azureblob` as the driver. Then in your jobs configuration, ensure you have cross-referenced the mount. As the last step of your task, you can copy your files to the appropriate bound location (you can utilize various [Azure Batch Environment Variables](https://docs.microsoft.com/azure/batch/batch-compute-node-environment-variables#environment-variables) to help disambiguate your destination path/location.

**Comment by sebastiankochman** [comment]
Thank you! I have used a variation of option 2 - I have mounted a shared data volume and then just modified my tasks' "command" properties to the following:

```yaml
command: /bin/bash -c "mkdir -p $AZ_BATCH_NODE_SHARED_DIR/logs_volume/$AZ_BATCH_JOB_ID/$AZ_BATCH_TASK_ID &&   [original command line content]
> >(tee $AZ_BATCH_NODE_SHARED_DIR/logs_volume/$AZ_BATCH_JOB_ID/$$AZ_BATCH_TASK_ID/stdout.log) 2> >(tee $AZ_BATCH_NODE_SHARED_DIR/logs_volume/$AZ_BATCH_JOB_ID/$$AZ_BATCH_TASK_ID/stderr.log >&2)"
```

Results in a bit long "command" property, but seems to work as expected!
