### ISSUE TITLE
Retrieving files in docker container

### ISSUE THREAD

**Issue by hildeweerts** [Azure/batch-shipyard#181]
I'd like to log some results of my batch tasks by saving files in the docker container. What is the best way to retrieve those files when using batch-shipyard?

Thanks!

**Comment by alfpark** [comment]
You can use the following commands:

To list files on the node:
- `data files list` (with optional arguments `--jobid` and `--taskid`)
    - Example: `data files list --jobid myjob --taskid task-00000`
- `data files task` with the argument `--filespec` of `jobid,taskid,filename` or with `--all` and optional `--filespec`.
    - Example: `data files task --filespec `myjob,task-00000,stdout.txt`
- `data files node` which is similar to the `data files task` above, but operates at the node level.

All of these commands can be found in the [usage guide](http://batch-shipyard.readthedocs.io/en/latest/20-batch-shipyard-usage/#data-command).

If you want a graphical way to interact with your files, you can use BatchLabs.

**Comment by hildeweerts** [comment]
Unfortunately, I had to change the working directory in order to have my docker containers work properly (otherwise I got a File doesn't exist error). Is there a way to persist the files of a non-default working directory as well?

**Comment by alfpark** [comment]
It's best if you just redirect your output (via a program configuration option or redirect if piping) to the task working directory.

If that is not an option, you can map whatever directory back into the host using `data_volumes` (under `global_resources`:`volumes`) in config.yaml or specifying a `-v` mapping for your task in the `additional_docker_run_options`.

Additionally, if you need to persist such files to Azure Storage, you can take a look at the `shared_data_volumes` `azurefile` and `azureblob` support in config.yaml.
