### ISSUE TITLE
Not using Docker when executing jobs

### ISSUE THREAD

**Issue by lewisKit** [Azure/batch-shipyard#182]
Hi,

I have some program that can not run in dockers, so is there a way not to use docker or singularity image to execute jobs locally using batch-shipyard?

**Comment by alfpark** [comment]
Batch Shipyard is a system which enforces containerized execution. There is no supported way to use Batch Shipyard for executing non-containerized tasks.

I'm curious to know what program you have that cannot run in a container?

**Comment by lewisKit** [comment]
Thank you for the explanation. 

 I want to run some reinforcement learning algorithms using mujoco, but I don't have an institute license for that, and the personal education license cannot run in a docker container, the only way to run that is to use a custom image without docker containers.

**Comment by alfpark** [comment]
In that case, you can use the [Azure CLI](https://docs.microsoft.com/azure/batch/batch-cli-get-started) to drive your execution on Azure Batch using json configuration, programmatically access Azure Batch through an [SDK](https://docs.microsoft.com/azure/batch/), or graphically submit using [Azure Portal](https://portal.azure.com/) or [BatchLabs](https://github.com/Azure/BatchLabs).

**Comment by lewisKit** [comment]
Thanks for suggestions! I am currently directly using Azure batch SDK to launch such jobs.
