### ISSUE TITLE
Docker command is not executed in the container working directory

### ISSUE THREAD

**Issue by lgilz** [Azure/batch-shipyard#190]
I would expect that the command in the job description `job_specifications.tasks.command` of the `jobs.yaml` leads to the same result as when I use `docker run`. However, the command option in the job definition seems to overwrite the containers working directory to be `$AZ_BATCH_TASK_WORKING_DIR`. This is a non-standard procedure and very confusing. 

I would expect that `shipyard jobs add` with the following `jobs.yaml` produces the same output as `docker run busybox pwd`. 

Instead `docker run busybox pwd` outputs `/` and the shipyard job outputs `/mnt/batch/tasks/workitems/test/job-1/task-00007/wd`. Therefore, if I would want to run code in my own container, I first had to change to the right working directory. I would very much appreciate if you change that behavior - or at least state this very clear in the documentation. 

jobs.yaml
```
job_specifications:
- id: test
  tasks:
  - docker_image: busybox
    command: pwd
```

**Comment by alfpark** [comment]
You are correct, this information is missing from the documentation.
