### ISSUE TITLE
shipyard is not accessible through Azure Cloud Shell

### ISSUE THREAD

**Issue by whataride** [Azure/batch-shipyard#207]
I logged into my Azure cloud shell, and typed in `shipyard`, but wasn't able to invoke it. Should I do something else?

![image](https://user-images.githubusercontent.com/6028927/41066921-8599101c-6998-11e8-8bec-5cc2c39ec472.png)

**Comment by alfpark** [comment]
You're correct; apologies with Batch Shipyard suddenly disappearing from Cloud Shell. There was an issue with a dependent package which broke Batch Shipyard installs. It had to be temporarily removed while the bug was fixed.

The plan is to re-enable it with the upcoming 3.5.0b2 release.

**Comment by alfpark** [comment]
Tentatively by next week.

**Comment by alfpark** [comment]
Batch Shipyard is available again in Cloud Shell. Thanks for your patience.

**Comment by whataride** [comment]
I just checked and it works now. Thanks!
