### ISSUE TITLE
"azure blob mounting is not supported" even when image is supported

### ISSUE THREAD

**Issue by JanVanMeirvenne** [Azure/batch-shipyard#213]
Due to a change in the detection for image sku's incompatible with blobfuse, the logic incorrectly blocks on valid images.

`   if ((offer == 'ubuntuserver' and sku < '16.04-lts') or
                        not offer.startswith('centos') or
                        publisher != 'microsoft-azure-batch'):
                    raise ValueError(
                        ('azure blob mounting is not supported '
                         'on publisher={} offer={} sku={}').format(
                             publisher, offer, sku))`

Because multiple conditions are checked within one OR statement, it will basically always return TRUE and thus fail validation.

**Comment by alfpark** [comment]
Apologies, this logic was supposed to be removed. I'll hotfix and release as soon as possible.
