### ISSUE TITLE
depends_on causes shipyard-jmtask to fail with "ModuleNotFoundError: No module named 'ruamel'"

### ISSUE THREAD

**Issue by sebastiankochman** [Azure/batch-shipyard#221]
shipyard-jmtask fails with the following stderr:

```
cat: .shipyard-jmtask.envlist: No such file or directory
2018-06-27 22:30:53,722Z DEBUG __main__:_create_credentials:109 creating batch client for account url: https://sebastkobatchtest.westus2.batch.azure.com/
2018-06-27 22:30:53,732Z DEBUG __main__:main:255 loading pickled task map
Traceback (most recent call last):
  File "/opt/batch-shipyard/recurrent_job_manager.py", line 283, in <module>
    main()
  File "/opt/batch-shipyard/recurrent_job_manager.py", line 257, in main
    task_map = pickle.load(f, fix_imports=True)
ModuleNotFoundError: No module named 'ruamel'
```

Job spec looks like this:

```yaml
job_specifications:
- id: xxx
  auto_complete: true
  recurrence:
    schedule:
      recurrence_interval: 0.00:02:00
  tasks:
  - id: download_data
    docker_image: microsoft/cntk:2.5.1-cpu-python3.5
    input_data:
      azure_storage:
      - storage_account_settings: mystorageaccount
        remote_path: scripts/cntk
        local_path: $$AZ_BATCH_TASK_WORKING_DIR
        is_file_share: true
    output_data:
      azure_storage:
      - storage_account_settings: mystorageaccount
        remote_path: output/data
        local_path: $$AZ_BATCH_TASK_WORKING_DIR/data
        is_file_share: false
    max_task_retries: 0
    max_wall_time: 00:10:00
    command: /bin/bash -c "source /cntk/activate-cntk && [...]"
  - id: train
    docker_image: microsoft/cntk:2.5.1-cpu-python3.5
    depends_on:
    - download_data
    [...]
```

I needed to use depends_on + passing data through Azure Storage, because of the other issue blocking me from using "azure_batch" as input_data: https://github.com/Azure/batch-shipyard/issues/29

I would appreciate your help!

**Comment by alfpark** [comment]
This was caused by a subtle issue with the yaml parser/loader and pickling.

**Comment by sebastiankochman** [comment]
I validated that the fix in "develop" branch has solved my problem - thank you very much!

**Comment by speschl** [comment]
@alfpark What was the fix for #221? I'm still running in the same issue and I'm using the "depends_on" attribute in my dependent task as mentioned #29.

**Comment by alfpark** [comment]
Which version are you using?

**Comment by speschl** [comment]
Hey Fred,
Thanks for getting back to me. I'm using 3.7.0 (installed about 2 months ago). 

Regards,
Sterling Peschl
    On Thursday, August 29, 2019, 11:52:02 AM CDT, Fred Park <notifications@github.com> wrote:  
 
 
Which version are you using?

**Comment by alfpark** [comment]
Can you open a new issue with relevant error output and configuration?

**Comment by speschl** [comment]
@alfpark I created a new issue #306.
