### ISSUE TITLE
Workaround for `auto_pool` with GlusterFS on Compute?

### ISSUE THREAD

**Issue by mesnardo** [Azure/batch-shipyard#225]
Hello @alfpark,

It appears that `auto_pool` cannot be used along with a GlusterFS on compute nodes.
Is there an alternative to automatically deallocate a compute pool once the jobs and tasks are completed when using GlusterFS on Compute?

Ideally, I would like to automatically (1) provision a pool upon jobs submission, (2) ingress data to GlusterFS,  (3) egress output data to a persistent Azure Storage File Share, and (4) automatically deallocate the pool (once the job is completed).
So far, I am using:
```
shipyard pool add --configdir config
shipyard data ingress --configdir config
shipyard jobs add --configdir config
```
((3) is done with `output_data` under the relevant task in `jobs.yaml`.)

Thank you for your help.

Batch Shipyard release used: `3.5.0`.

**Comment by alfpark** [comment]
Unfortunately, the pool creation must be synchronous with the CLI call in order to enable glusterfs on compute (due to the coordinated setup that is required).

If you can drive your scenario through a shell script, you could do something like what you have with a few tweaks:

```shell
export SHIPYARD_CONFIGDIR=config
# no need for autopool
shipyard pool add
shipyard data ingress
shipyard jobs add
shipyard jobs tasks list --poll-until-tasks-complete
shipyard pool del -y
unset SHIPYARD_CONFIGDIR
```

**Comment by mesnardo** [comment]
Wonderful! Thank you @alfpark for the workaround.
This issue can be closed whenever you want.
