### ISSUE TITLE
Clarify use cases after Batch got native Docker support

### ISSUE THREAD

**Issue by letmaik** [Azure/batch-shipyard#226]
In the past Batch didn't have any support for containers, so Shipyard was more or less the only way to do it without much effort.

Now that Batch has [Docker support](https://docs.microsoft.com/en-gb/azure/batch/batch-docker-container-workloads) the following question arises: When is it enough to just use raw Batch, and when does it make sense to use Shipyard instead? This is all about Docker, so let's ignore Singularity for now.

**Comment by alfpark** [comment]
If your scenario is covered by and you are comfortable using the Azure Batch SDK (or Azure CLI, graphical UIs), then utilizing container support in core Azure Batch is most likely sufficient - as outlined in the document you linked.

That being said, there are a plethora of features and enhancements that Batch Shipyard provides outside of "just" container support. The major features are [summarized on the main page README](https://github.com/Azure/batch-shipyard#major-features); there are only a few bullet points on the list that overlap with core Azure Batch container support. Support for [new features](https://github.com/Azure/batch-shipyard/blob/master/docs/97-faq.md#how-do-new-versions-and-backward-compatiblity-work) will also continue to evolve in Batch Shipyard.

As an aside, Batch Shipyard can utilize ["native" container support](https://github.com/Azure/batch-shipyard/blob/master/docs/25-batch-shipyard-platform-image-support.md) as well, which can provide for an improved experience if your [scenario is amenable](https://github.com/Azure/batch-shipyard/blob/master/docs/97-faq.md#what-is-native-under-pool-platform_image-and-custom_image). Many enhancements that Batch Shipyard provides work transparently with "native" Docker supported pools.
