### ISSUE TITLE
Egress data to Azure Storage if task completes with non-zero code

### ISSUE THREAD

**Issue by mesnardo** [Azure/batch-shipyard#229]
Hello!

I am running a multi-instance task, using GlusterFS on compute, through a shell script to automatically delete the compute pool once the job completes:
```
#!/usr/bin/env bash

export SHIPYARD_CONFIGDIR=config
shipyard pool add --yes
shipyard data ingress
shipyard jobs add
shipyard jobs tasks list --poll-until-tasks-complete
shipyard pool del --yes
shipyard jobs del --yes
unset SHIPYARD_CONFIGDIR
```

The `jobs.yaml` configuration file contains an `output_data` object to egress the output of the task to Azure Storage File Share once the task is completed.

However, my task fails at some point and the pool is deleted without the output data being egressed to Azure Storage.
(The task and job are now tagged as `Completed (FailureExitCode)` and `Completed`, respectively.)

Is it possible to egress data automatically to Azure Storage with Batch Shipyard in the event where the task exits with a non-zero code?
(According to the Batch Shipyard documentation, data are egressed if and only if the task completes successfully.)

I am using release `3.5.0` and the last two polls of the job are:
```
2018-07-16 15:46:27.133 INFO - list of tasks for job job-snake2d2k35
* task id: task-00000
  * job id: job-snake2d2k35
  * state: running @ 2018-07-16 16:53:50.408136+00:00
  * previous state: preparing @ 2018-07-16 16:53:50.079929+00:00
  * has upstream dependencies: False
  * default exit options:
    * job action: n/a
    * dependency action: n/a
  * max retries: 1
  * retention time: 2 days, 0:00:00
  * execution details:
    * pool id: pool-snake2d2k35
    * node id: tvm-1783593343_2-20180716t164233z
    * started: 2018-07-16 16:53:50.080017+00:00
    * completed: None
    * duration: n/a
    * retry count: 0
    * requeue count: 0
    * result: n/a
    * exit code: None
2018-07-16 15:46:32.224 INFO - list of tasks for job job-snake2d2k35
* task id: task-00000
  * job id: job-snake2d2k35
  * state: completed @ 2018-07-16 19:46:30.450612+00:00
  * previous state: running @ 2018-07-16 16:53:50.408136+00:00
  * has upstream dependencies: False
  * default exit options:
    * job action: n/a
    * dependency action: n/a
  * max retries: 1
  * retention time: 2 days, 0:00:00
  * execution details:
    * pool id: pool-snake2d2k35
    * node id: tvm-1783593343_2-20180716t164233z
    * started: 2018-07-16 16:53:50.080017+00:00
    * completed: 2018-07-16 19:46:30.450612+00:00
    * duration: 2:52:40.370595
    * retry count: 0
    * requeue count: 0
    * result: failure
    * exit code: 134
    * failure info: usererror
      * FailureExitCode: The task exited with an exit code representing a failure
        * Message: The task exited with an exit code representing a failure
```

Thanks!

**Comment by alfpark** [comment]
Can you use an `azurefile` shared data volume instead? You can specify the volume to mount and you can write directly to the Azure File Share while the container/task is running.

**Comment by mesnardo** [comment]
I am using HDF5 library with parallel I/O to output the data.
Correct me if I am wrong, but Azure Files do not seem appropriate for concurrent access to files.

**Comment by alfpark** [comment]
If it's not appropriate for writing while the program is running, you can wrap your execution to always copy output after the program completes, and then return the exit code. You could create a shell script either embedded in the container or as a task resource file, for example:

```shell
#!/usr/bin/env bash

/path/to/program $*
rc=$?
cp <source path> <azure file or blob mount path within the container>
exit $rc
```

Otherwise, this will need to be a feature request to allow upload regardless of task success/failure.

**Comment by alfpark** [comment]
Closing due to no response, please re-open if you have further questions. The conditional egress feature work has been logged as #230.
