### ISSUE TITLE
No module named 'pykwalify'

### ISSUE THREAD

**Issue by n17s** [Azure/batch-shipyard#242]
First time user. I got the following error. I know how to solve it but it would be nice to fix in master.

  File "c:\src\github\batch-shipyard\shipyard.py", line 47, in <module>
    import convoy.validator
  File "c:\src\github\batch-shipyard\convoy\validator.py", line 42, in <module>
    import pykwalify.core
ModuleNotFoundError: No module named 'pykwalify'

**Comment by alfpark** [comment]
How did you install?

**Comment by n17s** [comment]
- git clone
- install.cmd shipyard.venv
- tried to use it 

My fix was to activate the environment and pip install pykwalify.

**Comment by alfpark** [comment]
Did you run shipyard via the generated `shipyard.cmd`? I tried to repro this failure and cannot.

**Comment by alfpark** [comment]
Looks like you have this issue resolved on your end. I'll close this as I can't repro this.
