### ISSUE TITLE
Docker error when batch-shipyard attempts to run job: chdir to cwd(\"\") set in config.json failed: permission denied

### ISSUE THREAD

**Issue by sarahhp** [Azure/batch-shipyard#245]
#### Problem Description
I have run across a docker error when batch shipyard attempts to run my job and I just can’t figure out what’s going on.  That is the pool creation succeeds but the job execution fails.  Error text is: docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "chdir to cwd (\"/mnt/batch/tasks/workitems/snlacedryrun/job-1/task-00000/wd\") set in config.json failed: permission denied": unknown.
#### Batch Shipyard Version
3.6.0
#### Steps to Reproduce
I'm deploying from an azure VM (Ubuntu) using the following commands from the directory containing the configuration files: 
$SHIPYARD/shipyard pool add
$SHIPYARD/shipyard jobs add -v --tail stderr.txt
Also mounting three azure file shares to the docker container.  
#### Expected Results
job created
#### Actual Results
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "chdir to cwd (\"/mnt/batch/tasks/workitems/snlacedryrun/job-1/task-00000/wd\") set in config.json failed: permission denied": unknown.
#### Redacted Configuration
config.yml:
![image](https://user-images.githubusercontent.com/43327001/48928902-b6911000-ef37-11e8-96e3-2406cb03eee8.png)
jobs.yml:
![image](https://user-images.githubusercontent.com/43327001/48928974-59e22500-ef38-11e8-995f-2c293500d5d8.png)
#### Additional Logs
stdout to VM upon running shipyard jobs add:
![image](https://user-images.githubusercontent.com/43327001/48928867-54d0a600-ef37-11e8-9070-138468396d7b.png)
#### Additonal Comments
Not sure if this issue is stemming from my configuration setup, settings being passed to docker via shipyard, or is an underlying docker issue, sorry for that!  Any guidance appreciated.

**Comment by alfpark** [comment]
Can you retry your task without the `user_identity` section?

**Comment by sarahhp** [comment]
@alfpark yes thankyou that seems to fix the issue

**Comment by alfpark** [comment]
Great, one other minor thing with your config: you don't need to specify `additional_registries` under `global_resources`. That is only required if you are using Docker images which aren't specified to preload and have a registry login associated with them.

**Comment by sarahhp** [comment]
Ah I see.  Thanks!
