### ISSUE TITLE
Can I mix Linux and Windows containers in one pipeline?

### ISSUE THREAD

**Issue by veonua** [Azure/batch-shipyard#248]
#### Feature Request Description
It seems pipeline supports only one type of vm configuration.
For ML pipelines it would be nice to be able to mix Windows and Linux apps within the framework of Azure Batch

#### Describe Preferred Solution
It would be awesome if Azure batch shipyard automagically run appropriate type of the VM for the container and connect them via Azure framework

**Comment by alfpark** [comment]
There are three options available to enable your scenario:

1. Leverage [federations](https://github.com/Azure/batch-shipyard/blob/master/docs/68-batch-shipyard-federation.md) to federate a Linux and Windows pool together as a single logical resource.
2. Create two distinct pools, a Linux and Windows pool, and ensure you use a common storage fabric (e.g., Azure Storage File Shares, Azure Storage Blob, RemoteFS NFS with Samba, etc.) or use the built-in `input_data`:`azure_batch` task file movers to move data as necessary between tasks on disparate pools.
3. Try to leverage LCOW on Windows to run Linux and Windows containers on Windows Server 2019. I'm not sure if this is fully supported and may have limitations.

Azure Batch does not operate at the level of a VM as a resource. Batch pools, which may contain 0, 1, or more VMs, are where Batch jobs are scheduled.
