### ISSUE TITLE
Possible scenarios for using pool auto-resize?

### ISSUE THREAD

**Issue by lediur** [Azure/batch-shipyard#25]
I noticed in the "current issues" documentation that you recommend using batch-shipyard to resize pools.  I looked at the resizing code in `fleet.py` and `batch.py`, and I was wondering if there were scenarios where I could possibly use pool auto-resizing? e.g. if I didn't care about SSHing into nodes, and I didn't use GlusterFS.

**Comment by alfpark** [comment]
Pool autoscale is something that's been on the backlog. I can add an issue for it for possible inclusion in 3.0.0.

**Comment by alfpark** [comment]
Closing this, please continue discussion on #26 if necessary.
