### ISSUE TITLE
Add Batch environment variables to pool start task

### ISSUE THREAD

**Issue by jackpimbert** [Azure/batch-shipyard#252]
#### Feature Request Description
I would like to use the [Azure batch insights](https://github.com/Azure/batch-insights) to get some simple monitoring information via the Batch Explorer. To do so looks fairly straight forward, however I need to add some Batch environment variables that can be seen on start of a vm in a pool, and also from Batch Explorer. Therefore, using export isn't enough and instead the environment variables need to be added within the start task, e.g. https://github.com/Azure/batch-shipyard/blob/296c39b39bdb5b2a14d66d56a5e5a2be6ebfcbcb/convoy/fleet.py#L1520-L1523

#### Describe Preferred Solution
An option in the pool configuration to add custom environment variables, as is possible within the jobs configuration.

Please let me know if there's another way of adding environment variables to the start task, such that they will be included as Batch environment variables and seen within the Batch Explorer, thanks!

**Comment by alfpark** [comment]
Would it be helpful to provide a direct App Insights integration? This was on my backlog but wanted to provide a full Prometheus/Grafana monitoring solution that aligns with an open source solution.

**Comment by jackpimbert** [comment]
I would find it useful as a lighter weight monitoring solution in comparison to using Prometheus/Grafana. In our current use case it works better, although we may end up going for the full solution in the future.

**Comment by jackpimbert** [comment]
Should I close this issue now that #253 has been merged in?

**Comment by alfpark** [comment]
The issue will auto-close when the commit is merged to `master`.

The Batch Insights integration has been merged to `develop` in #259.
