### ISSUE TITLE
task factory to be able to create tasks for folders in Azure File storage

### ISSUE THREAD

**Issue by veonua** [Azure/batch-shipyard#257]
#### Feature Request Description
Now task factory able generate task for files, but it's impossible to spawn task per folder.

#### Describe Preferred Solution
ability to set folder task or file task without copying folders as they could be huge 

#### Describe Alternatives Considered
create empty files with special name per folder and make file task for these files.

**Comment by alfpark** [comment]
You can create multiple `task_factory` per job and use `remote_path` to scope appropriately (in addition to `include` and `exclude` filters).

**Comment by veonua** [comment]
how? I have various number folders, currently it is impossible to run task per folder in the root
