### ISSUE TITLE
Question about documentation page - Limitations

### ISSUE THREAD

**Issue by dedreira** [Azure/batch-shipyard#261]
Hi all, 

I'm reading in your doc [page](https://batch-shipyard.readthedocs.io/en/latest/99-current-limitations/) the following:

Only Intel MPI (or polling-based IB uverbs) can be used in conjunction Infiniband/RDMA on Azure Linux VMs. This is a current limitation of the underlying VM and host drivers.

What does "polling-based IB uverbs" mean? can anyone tell me an example about these polling-based IB uverbs? It's OpenMPI a polling-based IB uverb?

Thanks in advance

**Comment by alfpark** [comment]
OpenMPI is not supported over IB/RDMA on current GA VM sizes. The forthcoming [Hc/Hb VMs](https://azure.microsoft.com/blog/introducing-the-new-hb-and-hc-azure-vm-sizes-for-hpc/) has SRIOV support for the IB/RDMA Mellanox NIC and will support all IB uverbs, and thus OpenMPI and many other MPI implementations.

Once Hc/Hb support is provided in Batch proper, the appropriate adjustments in Batch Shipyard will be made.
