### ISSUE TITLE
Docker Image for Snakemake Not Being Downloaded to Compute Nodes

### ISSUE THREAD

**Issue by markpearl** [Azure/batch-shipyard#267]
I have come across an issue where my tasks submitted using the Batch Shipyard command line tools are stuck in the Preparing state because the Docker image they depend on is not present on the Batch compute node.

After dealing with the issue for quite some time, I created an admin user on the compute node and logged in using ssh. I manually downloaded my Docker image, which is placed in a private registry, and then ran my task again. This time the task failed again and is hanging.

Provided are my configuration files:

config.yaml
![image](https://user-images.githubusercontent.com/44413695/54507839-a4d5dd00-4919-11e9-9017-d40b7cfaaa8c.png)

![image](https://user-images.githubusercontent.com/44413695/54507872-c767f600-4919-11e9-9eaa-93cb82792c7a.png)

![image](https://user-images.githubusercontent.com/44413695/54507895-d8186c00-4919-11e9-9556-979d762c9d82.png)

![image](https://user-images.githubusercontent.com/44413695/54507916-ebc3d280-4919-11e9-995c-89a84e402755.png)

Dockerfile used to create the image:

FROM biocontainers/biocontainers:latest

RUN conda install trimmomatic

WORKDIR /home/mjpearl/fileshare

CMD ["trimmomatic"]

This image is stored in my container registry under the trimmomatic repo and trimmomatic for the tag (i.e. trimmomatic: trimmomatic ). 

As per azure-hpc example, my snakemake workflow file is creating a shell script with the following command:

mjpearl@controlvm:~/fileshare/snakemake$ $SHIPYARD/shipyard pool add --configdir $FILESHARE/snakemake/azurebatch

The pool get's created successfully, and as soon as I see that the pool reaches "starting" stats i Abort the command. 

When I run the snakemake workflow the job just hangs:

![image](https://user-images.githubusercontent.com/44413695/54507685-cbdfdf00-4918-11e9-9dd2-00387904a61a.png)

For the batch account, the start task for the dedicated node seems to fail:

![image](https://user-images.githubusercontent.com/44413695/54507725-021d5e80-4919-11e9-97e5-382a3fe7f903.png)

Also provided are the stderr.txt and stdout.txt, respectively:

Stderr.txt:
mount error(2): No such file or directory
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)

Stdout.txt:
Linux 7bdca5853a074102b5577ae7ba27e2e1000000 4.18.0-1013-azure #13~18.04.1-Ubuntu SMP Thu Feb 28 23:48:47 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
2019-03-18T04:51:49,180846313+00:00 - INFO - Prep start

Configuration:
Custom image: 0
Native mode: 0
OS Distribution: ubuntu 18.04
Batch Shipyard version: 3.7.0
Blobxfer version: 1.7.0
Singularity version: 
User mountpoint: /mnt
Mount path: /mnt/batch/tasks/mounts
Batch Insights: 0
Prometheus: NE=, CA=,
Network optimization: 0
Encryption cert thumbprint: 
Install Kata Containers: 0
Default container runtime: runc
Install BeeGFS BeeOND: 0
Storage cluster mount: 
Custom mount: 
Install LIS: 
GPU: 
Azure Blob: 0
Azure File: 1
GlusterFS on compute: 0
HPN-SSH: 0
Enable Azure Batch group for Docker access: 
Fallback registry: 
Docker image preload delay: 0
Cascade via container: 1
P2P: 0
Block on images: trimmomatic/trimmomatic#

2019-03-18T04:51:49,296618240+00:00 - INFO - LIS installation not required
2019-03-18T04:51:49,305637489+00:00 - INFO - Mounting Azure File

**Comment by alfpark** [comment]
Duplicate, closing in favor of #268.
