### ISSUE TITLE
Not Able to Force Job to be Killed

### ISSUE THREAD

**Issue by markpearl** [Azure/batch-shipyard#269]
I'm trying to kill a job without user input and it doesn't seem to be working. 

Currently I have:

"$SHIPYARD/shipyard jobs del --configdir $FILESHARE/snakemake/azurebatch/samtools && sleep 30"

However it prompts we to kill the job. Is there a way I can force this command without having user input to intervene?

**Comment by alfpark** [comment]
Use the `-y` flag.

Please see the [documentation](https://github.com/Azure/batch-shipyard/blob/master/docs/20-batch-shipyard-usage.md) or issue `--help` to commands.
