### ISSUE TITLE
Batch Pool Configuration

### ISSUE THREAD

**Issue by markpearl** [Azure/batch-shipyard#270]
There doesn't seem to be an option to specify a different vm_size for low priority nodes when compared to dedicated nodes? Is there a way to do this?

pool_specification:
  id: agcanpooltrimmomatic
  vm_configuration:
    platform_image:
      offer: UbuntuServer
      publisher: Canonical
      sku: 18.04-LTS
  vm_count:
    dedicated: 4
    low_priority: 2
  vm_size: Standard_F16
  reboot_on_start_task_failed: false
  block_until_all_global_resources_loaded: true
  ssh:
    username: docker

**Comment by alfpark** [comment]
This is a Batch limitation. A pool is a homogeneous resource and the VM size is the same for all VMs in the pool. You will need to explore if [federations](https://github.com/Azure/batch-shipyard/blob/master/docs/68-batch-shipyard-federation.md) are applicable for your scenario.
