### ISSUE TITLE
Running Job Preparation task

### ISSUE THREAD

**Issue by rjtshrm** [Azure/batch-shipyard#273]
How can I run **Job Preparation tasks** (those are non containerized tasks) in Batch shipyard. Do I need to make them containerized because Batch shipyard only support container tasks and also they are like regular tasks (as there is no option for job preparation tasks), because I can download input files for job but can only execute tasks inside **tasks section** in Jobs.yaml file.

**Comment by alfpark** [comment]
Can you explain a bit further about your scenario on why you need a custom job prep task?

This request is backlogged on #202.

**Comment by rjtshrm** [comment]
Actually I am running some task using Docker containers. These Docker containers uses host volumes to read some file and these files (zip files) need to be downloaded on machine while starting the Job. I already have used Azure Batch Services and did the downloading and unzipping on file share path (Azure file share on each vm) of each node in Batch and then this path is mounted inside the Docker containers. Since, I have two container that will do the main tasks. But for unzipping of files and some bash operation, can I do as Command line in batch shipyard and do I also need to create a separate docker container for that. As of my knowledge, Azure Batch Shipyard accepts only Docker container tasks not the command line in the job.

**Comment by alfpark** [comment]
All regular tasks in Batch shipyard are container-based. Only node prep commands run on the host in Batch Shipyard. If you need to do this on a per-node basis, then you can utilize that functionality instead.

Allowing the use of job prep is planned as per above.

**Comment by vincenzobaz** [comment]
What about the `start_task`? Is it possible to modify it? If yes how?

 I just need it for [batch-insight](https://github.com/Azure/batch-insights#configure-your-azure-batch-pool-start-task)

**Comment by alfpark** [comment]
You can enable Batch Insights directly via the pool configuration:

https://github.com/Azure/batch-shipyard/blob/2301e20cfca33a3e6546285245d8acb94b8ce77c/config_templates/pool.yaml#L122

Closing this issue as the original ask for job prep is already cataloged in #202.
