### ISSUE TITLE
Exception in task_file_mover when ingressing files from other batch tasks

### ISSUE THREAD

**Issue by lediur** [Azure/batch-shipyard#29]
I've set up a job which contains several fetch tasks, and a single processing task that depends on the fetch tasks. For convenience, I tried using the Azure Batch `input_data` type in the processing task to get all the data from the preceding fetch tasks, but I'm running into this exception with `task_file_mover`.

```
Traceback (most recent call last):
  File "task_file_mover.py", line 148, in <module>
    main()
  File "task_file_mover.py", line 123, in main
    batch_client = _create_credentials()
  File "task_file_mover.py", line 60, in _create_credentials
    ba, url, bakey = os.environ['SHIPYARD_BATCH_ENV'].split(';')
ValueError: not enough values to unpack (expected 3, got 2)
```

I'm using KeyVault for supplying the batch credentials, like:

```json
{
    "credentials": {
        "batch": {
            "account": "myaccount",
            "account_key_keyvault_secret_id": "https://myvault.vault.azure.net/secrets/batchkey",
            "account_service_url": "https://myaccount.westus.batch.azure.com"
        }
    }
}
```

**Comment by alfpark** [comment]
I cannot repro this failure. If you use your account key instead of keyvault, does it succeed?

**Comment by lediur** [comment]
Yeah, this is still happening if I use account keys instead of keyvault. Is there any other info that might be helpful?

**Comment by alfpark** [comment]
Can you provide a simple jobs.json that can repro this failure, perhaps using toy docker images like helloworld?

**Comment by lediur** [comment]
Will do - here's a quick one I came up with:

**jobs.json**
```json
{
    "job_specifications": [
        {
            "id": "batch_transfer_test",
            "tasks": [
                {
                    "id": "start",
                    "image": "hello-world"
                },
                {
                    "id": "collect",
                    "depends_on": [ "start" ],
                    "image": "hello-world",
                    "input_data": {
                        "azure_batch": [
                            {
                                "job_id": "batch_transfer_test",
                                "task_id": "input"
                            }
                        ]
                    }
                }
            ]
        }
    ]
}
```

All the configs below are ones I'm currently using

**pool.json**
```json
{
    "pool_specification": {
        "id": "mypool",
        "vm_size": "STANDARD_A2M_V2",
        "vm_count": 10,
        "max_tasks_per_node": 2,

        "publisher": "Canonical",
        "offer": "UbuntuServer",
        "sku": "16.04.0-LTS",

        "ssh": {
            "username": "myuser"
        },

        "reboot_on_start_task_failed": true,
        "block_until_all_global_resources_loaded": true
    }
}
```

**config.json**
```json
{
    "batch_shipyard": {
        "storage_account_settings": "batch"
    },
    "docker_registry": {
        "private": {
            "server": "myregistry.azurecr.io"
        }
    },
    "global_resources": {
        "docker_images": [
            "myimage"
        ]
    }
}
```

**credentials.json**
```json
{
    "credentials": {
        "batch": {
            "account": "mybatchaccount",
            "account_key_keyvault_secret_id": "https://myvault.vault.azure.net/secrets/batch-mybatchaccount",
            "account_service_url": "https://mybatchaccount.westus.batch.azure.com"
        },
        "storage": {
            "batch": {
                "account": "mybatchstorage",
                "account_key_keyvault_secret_id": "https://myvault.vault.azure.net/secrets/storage-batch"
            },
            "data": {
                "account": "mydatastorage",
                "account_key_keyvault_secret_id": "https://myvault.vault.azure.net/secrets/storage-data"
            }
        },
        "docker_registry": {
            "myregistry.azurecr.io": {
                "username": "<guid>",
                "password_keyvault_secret_id": "https://myvault.vault.azure.net/secrets/acr"
            }
        }
    }
}
```

**Comment by alfpark** [comment]
@lediur Thanks for the repro files. I think I found the culprit to this issue. Unfortunately there is no quick fix to this issue outside of providing enabling credential encryption.

I'll try to package up a new release with task retention time constraint changes for release soon.

**Comment by lediur** [comment]
Okay - no worries! I can use blob storage instead with no issues; I just wanted to bring this to your attention. If I wanted to use batch storage transfer in the future, I would need to set up the credential encryption as specified in `config.json` with a PFX cert?

**Comment by alfpark** [comment]
@lediur I appreciate the bug reports/issues you are filing. That's correct, you can follow [this guide](https://github.com/Azure/batch-shipyard/blob/master/docs/75-batch-shipyard-credential-encryption.md) to enable credential encryption.

You will be able to use unencrypted credentials (as you have it now) for batch task data ingress once I get my fix in, which will land in develop soon.

**Comment by sebastiankochman** [comment]
I still see a similar issue, although perhaps the root cause is different now (I see in the original post there were 2 values found, in my case there is just 1):

`
Traceback (most recent call last):
  File "/opt/batch-shipyard/task_file_mover.py", line 173, in <module>
    main()
  File "/opt/batch-shipyard/task_file_mover.py", line 148, in main
    batch_client = _create_credentials()
  File "/opt/batch-shipyard/task_file_mover.py", line 63, in _create_credentials
    ba, url, bakey = os.environ['SHIPYARD_BATCH_ENV'].split(';')
ValueError: not enough values to unpack (expected 3, got 1)
`

Job spec looks like this:

`
job_specifications:
- id: my_job
  auto_complete: true
  recurrence:
    schedule:
      recurrence_interval: 0.00:02:00
  tasks:
  - id: download_data
    docker_image: microsoft/cntk:2.5.1-cpu-python3.5
    input_data:
      azure_storage:
      - storage_account_settings: mystorageaccount
        remote_path: scripts/cntk
        local_path: $AZ_BATCH_TASK_WORKING_DIR
        is_file_share: true
    max_task_retries: 0
    max_wall_time: 00:10:00
    command: /bin/bash -c "source /cntk/activate-cntk && [...]"
  - docker_image: microsoft/cntk:2.5.1-cpu-python3.5
    input_data:
      azure_batch:
      - job_id: my_job
        task_id: download_data
        destination: $AZ_BATCH_TASK_WORKING_DIR
      azure_storage:
      - storage_account_settings: mystorageaccount
        remote_path: scripts/cntk
        local_path: $AZ_BATCH_TASK_WORKING_DIR
        is_file_share: true
    max_task_retries: 0
    max_wall_time: 00:10:00
    command: /bin/bash -c "source /cntk/activate-cntk && [...]"
`

Is there any simple workaround, besides using Azure Storage to pass the output from one task to another?
I'd appreciate your help!

**Comment by alfpark** [comment]
Are you using credential encryption?

**Comment by sebastiankochman** [comment]
No - how can I enable it?

**Comment by alfpark** [comment]
You don't need to enable it for this to work. It's just so I can narrow down the culprit. I updated my comment from earlier, can you please respond to the other questions?

**Comment by sebastiankochman** [comment]
Tasks for responding! Answers to your questions:

1. Not using credential encryption, AFAIK (unless it's enabled by default)
2. Command line from both tasks:

download_data:
```
/bin/bash -c 'set -e; set -o pipefail; set -f; $AZ_BATCH_NODE_STARTUP_DIR/wd/shipyard_blobxfer.sh "1.2.1,i,False,<STORENAME>,core.windows.net,se=[...]&sp=rl&sv=2017-07-29&sr=s&sig=[...],scripts/cntk,$AZ_BATCH_TASK_WORKING_DIR,--mode file "; set +f; [ -f .shipyard.envlist ] && export $(cat .shipyard.envlist | xargs); env | grep AZ_BATCH_ >> .shipyard.envlist; docker run --rm --name xxx-download_data -v $AZ_BATCH_NODE_ROOT_DIR:$AZ_BATCH_NODE_ROOT_DIR -w $AZ_BATCH_TASK_WORKING_DIR --env-file .shipyard.envlist microsoft/cntk:2.5.1-cpu-python3.5 /bin/bash -c "source /cntk/activate-cntk && pip install --upgrade pip && pip freeze > pip-freeze.txt && pip install -r cntk/requirements.txt && python -u $AZ_BATCH_TASK_WORKING_DIR/cntk/download_data.py"; set -f; $AZ_BATCH_NODE_STARTUP_DIR/wd/shipyard_blobxfer.sh "1.2.1,e,False,<STORENAME>,core.windows.net,se=[...]&sp=rwdl&sv=2017-07-29&sr=c&sig=[...],output/data,$AZ_BATCH_TASK_WORKING_DIR/data,"; set +f; wait'
```

second task (which fails):
```
/bin/bash -c 'set -e; set -o pipefail; set -f; docker run --rm -t -v $AZ_BATCH_NODE_ROOT_DIR:$AZ_BATCH_NODE_ROOT_DIR -w $AZ_BATCH_TASK_WORKING_DIR -e "AZ_BATCH_NODE_STARTUP_DIR=$AZ_BATCH_NODE_STARTUP_DIR" alfpark/batch-shipyard:3.5.0b3-cargo /opt/batch-shipyard/task_file_mover.sh {{args}}; set +f;set -f; $AZ_BATCH_NODE_STARTUP_DIR/wd/shipyard_blobxfer.sh "1.2.1,i,False,<STORENAME>,core.windows.net,se=[...]&sp=rl&sv=2017-07-29&sr=s&sig=[...],scripts/cntk,$AZ_BATCH_TASK_WORKING_DIR,--mode file "; set +f; [ -f .shipyard.envlist ] && export $(cat .shipyard.envlist | xargs); env | grep AZ_BATCH_ >> .shipyard.envlist; docker run --rm --name xxx-train -v $AZ_BATCH_NODE_ROOT_DIR:$AZ_BATCH_NODE_ROOT_DIR -w $AZ_BATCH_TASK_WORKING_DIR --env-file .shipyard.envlist microsoft/cntk:2.5.1-cpu-python3.5 /bin/bash -c "source /cntk/activate-cntk && pip install --upgrade pip && pip freeze > freeze.txt && pip install -r cntk/requirements.txt && python -u $AZ_BATCH_TASK_WORKING_DIR/cntk/train_cntk.py"; wait'
```

3. You mean that I should add "depends_on"? When I do that, then I see this issue: https://github.com/Azure/batch-shipyard/issues/221 Also, when I observe execution of the tasks, it seems that second task is not started until 'download_data' completes, so I guess task dependency is implicit when input_data->azure_batch is used.

BTW, I have also tried the same spec, but without recurrence - I got exactly the same error.

**Comment by alfpark** [comment]
For the third point, you will want to enforce task dependencies. You are getting "lucky" in this case as the `download_data` task is getting scheduled ahead of the other task that requires those files and it is blocked for scheduling for reasons such as insufficient available slots on compute nodes.

**Comment by sebastiankochman** [comment]
I have validated that your fix in the "develop" branch has solved my problem - thank you very much!
I will also remember to use "depends_on" - thank you for pointing out! (perhaps you can consider updating documentation at http://batch-shipyard.readthedocs.io/en/latest/14-batch-shipyard-configuration-jobs/ where input_data -> azure_batch is mentioned?)
