### ISSUE TITLE
Clarity on OS for Infiniband/OMPI

### ISSUE THREAD

**Issue by gcormier** [Azure/batch-shipyard#304]
HC/HB IB support is vastly improved from the old H series.

I have IB working on HC44rs on vanilla Ubuntu 18.04, with UCX ( https://github.com/gcormier/hpc-fvcom/blob/master/azure/packer-ubuntu.sh )

Why does the OpenMPI example ( https://github.com/Azure/batch-shipyard/tree/master/recipes/mpiBench-Infiniband-OpenMPI ) for batch-shipyard require CentOS 7.6 HPC? Previously for H series this was the case/nightmare, but no longer.

**Comment by alfpark** [comment]
The current Marketplace Image from Canonical does not support Mellanox OFED out of the box. Once this is resolved, then there will be an update on the packer script to support this scenario and possibly the recipes.

**Comment by alfpark** [comment]
Ubuntu 16.04 + MOFED 4.6 works.

Ubuntu 18.04 MOFED support is pending (but works with default inbox drivers).

**Comment by alfpark** [comment]
Ubuntu 18.04 (with kernel 5.0) works with MOFED 4.7.
