### ISSUE TITLE
Documentation request for Windows container users

### ISSUE THREAD

**Issue by rykawagu** [Azure/batch-shipyard#311]
Hello,
In a situation of deploying Windows container with azure batch shipyard, there are not many samples for Windows container users. currently these YAML samples are mostly for Linux users.
It would be nice to add more samples and documentation for windows container user so that the users do not get confused with some gaps between operating systems in configuration.

I found two samples which are available on Github. but still not many:
https://github.com/Azure/batch-shipyard/tree/master/recipes/DotNet-Windows/config
https://github.com/Azure/batch-shipyard/blob/master/recipes/DiskSpd-Windows/

## actual senario
I would like to provide you with a senario why I filed this request:

during troubleshooting of deploying windows container with batch shipyard, a problem that we had was differences between operation systems, which are Windows and Linux environment.
At first, from documentation, we were expecting $AZ_BATCH_NODE_SHARED_DIR and all other environment variables to be expanded just as samples on github do.

### Expected jobs.yaml that did not work
```
input_data:
  ...
  local_path: $AZ_BATCH_NODE_SHARED_DIR
output_data:
  ...
  local_path $AZ_BATCH_NODE_SHARED_DIR
command: cmd /c $AZ_BATCH_NODE_SHARED_DIR/sample.exe
```

### Actual jobs.yaml that works
```
input_data:
  ....
  local_path: "%AZ_BATCH_NODE_SHARED_DIR%"

output_data:
  local_path "%AZ_BATCH_NODE_SHARED_DIR%"  (turned out we needed to add "")
command: cmd /c "%AZ_BATCH_SHARED_DIR%/sample.exe" (turned out we needed to replace it with the one in Windows style)
```

thus, although these were simple problems, it took a lot of time to find and fix. 
would be appreciate it if you considered.

Thanks,

**Comment by alfpark** [comment]
Documentation will be improved to point out general Linux vs. Windows environment variables in the jobs and pool documentation pages.

If you'd like to add a new or improve windows containers recipes, please feel free to submit a PR.
