### ISSUE TITLE
start task failed due to BlobNotFound

### ISSUE THREAD

**Issue by tswc** [Azure/batch-shipyard#317]
#### Problem Description
Start task failed
BlobNotFound: One of the specified Azure Blob(s) is not found
BlobSource: https://testshipyard.blob.core.windows.net/shipyardrf-clobotics-posm-report-v3/nvidia-driver_cc37.run?sr=b&sp=r&sig=hb0qFzw5L/eyHS5LGPPkdpDq2DgMbesFQfMHi%2BIzXnU%3D&sv=2018-03-28&se=2049-08-25T12%3A20%3A34Z
FilePath: /mnt/batch/tasks/startup/wd/nvidia-driver_cc37.run

all the node shows like this. I thought all the pre-scripts do not appear hear. 
I can not get the stderr.txt following the trouble shooting guide.

In the last month, all the programs run succussfully.
I don't know if there is something wrong with shipyard version.

#### Batch Shipyard Version
3.7.1
#### Redacted Configuration
```
INSERT RELEVANT YAML FILES
```

#### Additional Logs
```
INSERT ADDITIONAL LOGS HERE
```

**Comment by alfpark** [comment]
If I click the link for the BlobSource above, the error returned is container not found.

**Comment by tswc** [comment]
@alfpark  Thanks for reply.
Yes. What I mean is that this file should not be in my blob. The blob address in the error message is my own blob, but these scripts are official program from microsoft. These scripts should be downloaded and uploaded automatically.

Have I described it clearly?

**Comment by tswc** [comment]
The problem is that pool add does not show it failed. I think that is a bug, when I use batch shipyard 3.7.

**Comment by tswc** [comment]
Actually, when I use same shipyard config. It works with batch shipyard 3.7.1 successfully last month.
Now it does not work with 3.7.1 this month, but only work well with 3.8.2.  

> Yes, it should be downloaded/uploaded automatically, but the container is not found - how could the node start task work in this case?
That is not about if the containers is found or not.

**Comment by alfpark** [comment]
> The problem is that pool add does not show it failed. I think that is a bug, when I use batch shipyard 3.7.

If the *blob container* does not exist, the command to add the pool will fail.

> That is not about if the containers is found or not.

That's exactly what the error is about, `BlobNotFound`. It's the *blob container*, not the Docker container image.
