### ISSUE TITLE
Starting pool of N-Series silently fails in regions where they are not available

### ISSUE THREAD

**Issue by thdeltei** [Azure/batch-shipyard#32]
I tried to start a pool on Central US :
```json
{
    "pool_specification": {
        "id": "caffe-gpu",
        "vm_size": "STANDARD_NC6",
        "vm_count": 1,
        "publisher": "Canonical",
        "offer": "UbuntuServer",
        "sku": "16.04.0-LTS",
        "ssh": {
            "username": "docker"
        },
        "reboot_on_start_task_failed": false,
        "block_until_all_global_resources_loaded": true
    }
}
```
It silently failed:
```
2017-02-03 15:55:57,824Z DEBUG convoy.batch:_block_for_nodes_ready:290 waiting for 1 nodes to reach desired state
```
and I got a time-out on resize on the portal. 

I suspect it is because the N-Series are not available in Central US, but there was no error message that made that clear. I wonder if it would be possible to check the pool spec against the region availability?

**Comment by alfpark** [comment]
@thdeltei Unfortunately, there is no API available in the Batch service to validate if a SKU is available or not. There are a few ways to check this on your own:
1. Availability dashboard: https://azure.microsoft.com/en-us/regions/services/
2. Azure CLI, e.g.: azure vm sizes --location eastus
3. Azure CLI 2.0, e.g.: az vm list-sizes -l eastus
4. Azure Powershell
