### ISSUE TITLE
Azure blob not remounted after node restart

### ISSUE THREAD

**Issue by jakub-xen** [Azure/batch-shipyard#320]
#### Problem Description
If the batch node is restarted the mounted azure blob using blobfuse is not automatically remounted
#### Batch Shipyard Version
shipyard.py, version 3.8.2

#### Steps to Reproduce
Create a pool with 
  volumes:
    shared_data_volumes:
      azureblob_vol:

click reboot node from the web portal
#### Expected Results
azureblob volume should be mounted on start as with azure files
#### Actual Results
azureblob is not present
#### Redacted Configuration
```
INSERT RELEVANT YAML FILES
```

#### Additional Logs
```
INSERT ADDITIONAL LOGS HERE
```

**Comment by alfpark** [comment]
Please provide more information as requested in the redacted configuration section. Posting a `pool.yaml` at the minimum would be great (`config.yaml` would be good too, redacted as necessary).

**Comment by jakub-xen** [comment]
For reference:

config.yaml:
batch_shipyard:
  storage_account_settings: batchstore
global_resources:
  docker_images:
  - alpine
  - jakubjs/azopenfoamv1806-intel
  volumes:
    shared_data_volumes:
      azureblob_vol:
        volume_driver: azureblob
        storage_account_settings: batchstore
        azure_blob_container_name: blob
        container_path: $AZ_BATCH_NODE_SHARED_DIR/azblob
        mount_options:
        - --use-https=true
        bind_options: rw

pool.yaml:
pool_specification:
  id: workpool
  vm_configuration:
    platform_image:
      publisher: OpenLogic
      offer: CentOS-HPC
      sku: '7.4'
  vm_count:
    dedicated: 0
    low_priority: 1 
  vm_size: STANDARD_H16R
  inter_node_communication_enabled: true
  per_job_auto_scratch: true
  ssh:
    username: shipyard
  virtual_network: 
    name: xenof-vnet
    resource_group: xenof-group
    create_nonexistant: true
    address_space: 10.0.0.0/16
    subnet:
      name: batch-vm-subnet
      address_prefix: 10.0.0.0/18

**Comment by alfpark** [comment]
Thanks for the info, this has been fixed in the `develop` branch (and `develop-cli` Docker image).
