### ISSUE TITLE
Shipyard using deprecated Batch APIs?

### ISSUE THREAD

**Issue by sebastiankochman** [Azure/batch-shipyard#325]
#### Problem Description
I got an automated e-mail from Azure saying:

> Upgrade to the latest version of the Azure Batch REST API by October 31, 2020.
You're receiving this email because you use the Azure Batch Management REST API.
We've detected that you have used one or more deprecated Azure Batch Management REST API versions in the last 90 days.
These API versions have been marked for deprecation and will be removed on October 31, 2020, after which all requests using this version may fail. Find a list of the deprecated API versions that you're currently using in the Account Information section of this email.

I don't think I was using Azure Batch REST APIs directly, so I suspect Shipyard relies on some deprecated APIs - may it be correct?

#### Batch Shipyard Version
3.8.2 (although I most probably used older versions within the last 90 days as well)

**Comment by alfpark** [comment]
Batch Shipyard, as of the most recent version (3.8.2), does not use deprecated APIs:

Batch Service API (`azure-batch`) [hits](https://github.com/Azure/batch-shipyard/search?q=azure-batch%3D%3D&unscoped_q=azure-batch%3D%3D) are `8.0.0`.

Batch Management API (`azure-mgmt-batch`) [hits](https://github.com/Azure/batch-shipyard/search?q=azure-mgmt-batch%3D%3D&unscoped_q=azure-mgmt-batch%3D%3D) are `7.0.0`.

According to the [Batch API Status page](https://docs.microsoft.com/rest/api/batchservice/batch-api-status), neither of these are slated for near-term (within 1 year) deprecation.

In general, Batch Shipyard is updated to the latest available SDK on every major and minor release, so unless you're using a very outdated version of Batch Shipyard, it is not a concern if you follow the recommended advice to upgrade regularly.

Please note that you may be using an old version of Batch Explorer or some other tooling that may have triggered the email as well.

**Comment by alfpark** [comment]
Closing, please re-open if necessary.
