### ISSUE TITLE
Credential setup

### ISSUE THREAD

**Issue by mloubout** [Azure/batch-shipyard#337]
This is more of a question than an issue (I think), but is there a way to put multiple batch accounts, and more generally multiple credentials in the same yaml file, or  do I need to create one for each case?

**Comment by alfpark** [comment]
Currently, there is not. You will need to create one for each case. There are plans to do so in a future major revision, however.

**Comment by mloubout** [comment]
Ok, thank you, what I did but was wondering if there was an easier way.
