### ISSUE TITLE
workers stays indefinitely in preparation step when the docker image is not present    

### ISSUE THREAD

**Issue by javierbq** [Azure/batch-shipyard#347]
#### Problem Description
I started a job with  allow_run_on_missing_image: true on a pool that was intentionally missing the inage. I would expect the job to start once the image is automatically pulled into the worker node.  Instead of pulling the image the worker is stuck on prepartation with the following message:

2020-04-22T23:25:10,084071046+00:00 - INFO - blocking until Docker images ready: **.azurecr.io/**

#### Redacted Configuration
```
INSERT RELEVANT YAML FILES
```

#### Additional Logs
```
INSERT ADDITIONAL LOGS HERE
```

**Comment by alfpark** [comment]
Looks like your image name is malformed `.azurecr.io/`. Please ensure that your images are named and referenced correctly.
