### ISSUE TITLE
Simple Job Add does not end

### ISSUE THREAD

**Issue by youngmi97** [Azure/batch-shipyard#353]
#### Problem Description
We made configurations to the relevant .yaml files and the batch node is properly put into an idle state. However, adding a job to the queue does not end..

No further progression is made from this point on ..
![IMAGE 2020-07-02 16:46:00](https://user-images.githubusercontent.com/38910144/86331012-72bdcb00-bc83-11ea-8271-f2201e867ad4.jpg)

#### Batch Shipyard Version
3.9.1

The following are our configurations

<img width="197" alt="Screen Shot 2020-07-02 at 4 48 08 PM" src="https://user-images.githubusercontent.com/38910144/86331269-d21bdb00-bc83-11ea-93c4-1e4c5709efd1.png">
<img width="447" alt="Screen Shot 2020-07-02 at 4 48 14 PM" src="https://user-images.githubusercontent.com/38910144/86331276-d47e3500-bc83-11ea-99ff-f06cd8c412dd.png">
<img width="561" alt="Screen Shot 2020-07-02 at 4 48 20 PM" src="https://user-images.githubusercontent.com/38910144/86331277-d5af6200-bc83-11ea-8657-bee677e3fc67.png">
<img width="366" alt="Screen Shot 2020-07-02 at 4 48 25 PM" src="https://user-images.githubusercontent.com/38910144/86331279-d647f880-bc83-11ea-96ff-66a888619b25.png">

#### Additonal Comments
We think that there may be an issue with config.yaml or pool.yaml but not too sure..
We are testing on a simple docker image from python:latest.

**Comment by alfpark** [comment]
This may be due to your job being assigned to a different pool and the task not actually executing. Please double check with Batch Explorer, Portal, or the shipyard cli.

**Comment by alfpark** [comment]
Closing, please re-open if more information can be provided.
