### ISSUE TITLE
How to add tasks?

### ISSUE THREAD

**Issue by marcelvb** [Azure/batch-shipyard#36]
Hi,

I'm new to both Docker and Azure Batch, but I feel it is what I need. 

My use case:
I need to process batches of thousands of images. My input for each task is an xml file and 5 images. Then a Linux executable wrapped in a Python script processes this input and produces 3 images and an xml file as output. I wrapped the code in a Docker image that processes one set of images. Both the input and output files are in Azure blob storage. Also this process is part of a bigger automated pipeline and I need to monitor when the batch is done.

I used batch-shipyard to create a pool. Now my question is, how do create the job and its tasks (from code)? Am I supposed to generate a jobs.xml with thousands of tasks? Or is there another way? Can I use the Azure Bath API as well?

Thanks in advance for clarifying this.

**Comment by alfpark** [comment]
In the future, you will be able to programmatically do this yourself with #11. However, in the meantime, you can create a script that generates the jobs.json file for consumption.

Supporting "parametric sweep" style jobs is also something that is being considered for addition.
