### ISSUE TITLE
Create Pypi package for Batch Shipyard

### ISSUE THREAD

**Issue by eedokl** [Azure/batch-shipyard#365]
#### Feature Request Description
- Create Pypi package for Batch Shipyard, so that installation is simplified

#### Describe Preferred Solution
I have created a package for my own purposes - attached a patch file which moves some files, adds setup.py, does some tiny adjustements that allows to create a package.

#### Describe Alternatives Considered
None.

#### Additional Context
See patch file for the required changes to the repo.
I guess with that the installers could also be removed.
[batch_shipyard_pypi_package.zip](https://github.com/Azure/batch-shipyard/files/6760329/batch_shipyard_pypi_package.zip)

**Comment by alfpark** [comment]
Dupe: https://github.com/Azure/batch-shipyard/issues/196
