### ISSUE TITLE
Prefetching images upon pool creation

### ISSUE THREAD

**Issue by fuglede** [Azure/batch-shipyard#368]
In vanilla Batch, it is possible to prefetch Docker images upon pool creation, cf. https://docs.microsoft.com/en-us/azure/batch/batch-docker-container-workloads#prefetch-images-for-container-configuration

Is the same thing possible with Batch Shipyard, or is it only possible when creating jobs, and if so, does one run the risk of having to fetch the image upon each job creation? I wasn't able to find anything in the docs on the matter.

I suppose it's always possible to create the pool manually or with the SDKs, then just use Shipyard to handle the jobs themselves.

**Comment by alfpark** [comment]
Yes, please see: https://github.com/Azure/batch-shipyard/blob/master/docs/12-batch-shipyard-configuration-global.md
