### ISSUE TITLE
It can not start job by batch scheduler when VNET configured to use NAT gateway.

### ISSUE THREAD

**Issue by AndyPengYong** [Azure/batch-shipyard#371]
#### Problem Description
It can not start batch job by batch scheduler when VNET configured to use NAT gateway.
We run batch job through docker image which keep in Azure Container Registry

#### Batch Shipyard Version
The latest version
#### Steps to Reproduce
1. Configure any VNET in Azure and assign NAT gateway to the subnet of the VNET
2. Configure job.yaml with scheduler information

job_specifications:
- id: job_id
  auto_complete: true
  max_task_retries: 0
  recurrence:
    schedule:
      do_not_run_until: '2021-12-22 01:00:00+09:00'
      do_not_run_after: '2099-12-31 23:59:59+09:00'
      recurrence_interval: 00:15:00
      start_window: null
  auto_pool:
    keep_alive: false
    pool_lifetime: job
  tasks:
  - id: task01
    docker_image: xxxxx.azurecr.io/xxxx:v1.0
    command: python3 /xxxx/xxxx/xxxx/script.py

3. Pool.yaml
pool_specification:
  id: scrum-pool
  vm_configuration:
    platform_image:
      offer: centos-container
      publisher: microsoft-azure-batch
      sku: 7-8
  vm_count:
    dedicated: 1
    low_priority: 0
  vm_size: Standard_A2_v2
  additional_node_prep:
    environment_variables:
      AZURE_TENANT_ID: xxxxxxxxxxxxx
      AZURE_CLIENT_ID: xxxxxxxxxxxx
      AZURE_CLIENT_SECRET: xxxxxxxxxxxx
  virtual_network:
    arm_subnet_id: /subscriptions/xxxxxxxx/resourceGroups/rg-xxxxx/providers/Microsoft.Network/virtualNetworks/xxxx-vnet/subnets/xxx-xxx-xxxx

4. config.yaml
batch_shipyard:
  storage_account_settings: storageaccountname
global_resources:
  additional_registries:
    docker:
    - xxxxxx.azurecr.io
  docker_images: 
  - xxxxxxx.azurecr.io/xxxxxx:v1.2

5. credential.yaml
credentials:
  aad:
    authority_url: https://login.microsoftonline.com
    directory_id: xxxxxxxxxxxxxxxxxxxxxxx
    application_id: xxxxxxxxxxxxxxxxxxxxxxxx
    auth_key: xxxxxxxxxxxxxxxxxxxxxxx
  batch:
    account_service_url: https://xxxxxxxxxxx.japaneast.batch.azure.com
    resource_group: xxxxxxxxxxxxx
  storage:
    storageaccountname
      account: xxxxxxxxxxx
      endpoint: core.windows.net
      resource_group: xxxxxxxx
  docker_registry:
    xxxxxxxxxx.azurecr.io:
      username: xxxxxxxx
      password: xxxxxxxxxxxxxxxx
  management:
    subscription_id: xxxxxxxxxxxxxxxxxxxxxxxxxx

#### Expected Results
Batch job should be triggered successfully.
#### Actual Results
Batch job can not be triggered.

#### Additonal Comments
There is no issue to run the batch job through local machine by batch shipyard CLI

**Comment by alfpark** [comment]
NAT gateway in-between for job manager and authorization token is not supported in Azure Batch.
