### ISSUE TITLE
Documentation page links not working

### ISSUE THREAD

**Issue by ktakeda1** [Azure/batch-shipyard#4]
Links to guide and recipes not working on homepage (https://azure.github.io/batch-shipyard/) in Documentation section:

- Batch Shipyard Guide links to https://azure.github.io/batch-shipyard/docs (404 error)
- Batch Shipyard Recipes links to https://azure.github.io/batch-shipyard/recipes (404 error)

**Comment by alfpark** [comment]
@ktakeda1 Thank you for reporting the issue. Unfortunately the github.io page does not understand relative links (the page is generated from the main README file). I've corrected the REAMDE to use absolute links.
