### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by drcrook1** [Azure/batch-shipyard#40]
I am staring at the Tensor Flow recipes looking desperately for how to kick off my first load.  I have 150 gb sitting in data lake.  Do I provision Batch, do I set up VMs, what in the world do I need to do step by step to use random images in data lake with some random label file or set of label files.

**Comment by alfpark** [comment]
As far as I know, Azure Data Lake can only be accessed via WebHDFS REST API. You will need to modify your TF scripts to load data from your ADL store account so they can be locally accessible on each compute node.

As far as I know, WebHDFS support in fuse-dfs was never completed or has stalled indefinitely. Having that capability would trivially allow standard file system semantics in your applications.

**Comment by drcrook1** [comment]
So what is the point of this project then?

**Comment by alfpark** [comment]
This project is not limited in scope to TensorFlow and reading data from ADL. Sourcing your data out of ADL is not specific to this framework either, you'd need to do that even if you're manually provisioning your nodes in Azure and scheduling your work yourself.

Perhaps reading the [intro docs](https://github.com/Azure/batch-shipyard/blob/master/docs/00-introduction.md) is a good starting point for covering the goal of Batch Shipyard.
