### ISSUE TITLE
Consistent Key Error for Storage Account

### ISSUE THREAD

**Issue by philmea** [Azure/batch-shipyard#41]
I have encountered this consistently after rebuilding 4 times, key is not being recognized.

Command:
./batch-shipyard/shipyard.py pool add --credentials ./credentials.json --config ./config.json --pool ./pool.json

Error:
KeyError: '[storageaccountname]'

**Comment by alfpark** [comment]
@philmea Please ensure that your storage link alias is defined in `credentials.json` and you're referencing it properly from `config.json`. The name of the storage account may differ from the link name.

**Comment by philmea** [comment]
@alfpark It looks like the reference is properly configured, check below:

Credentials:
  "account": "airbatchtest",
                "account_key": "[key]",
                "endpoint": "https://airbatchtest.blob.core.windows.net/"

Config:
    "batch_shipyard": {
        "storage_account_settings": "airbatchtest"
    },

Suggestions?

**Comment by alfpark** [comment]
The storage credential from `config.json` is not referenced by the account name, it is referenced by its link name or alias.

Take a look at the template example: https://github.com/Azure/batch-shipyard/blob/master/config_templates/credentials.json#L22-L29

Or any of the recipes.

**Comment by philmea** [comment]
Ah! Thank you so much, I was really hitting my head against a wall there. The recipes are a great resource to complement the configuration documentation.
