### ISSUE TITLE
udi not running on 10-node CentOS D13_v2 pool

### ISSUE THREAD

**Issue by nick-phillips** [Azure/batch-shipyard#43]
Attempting to update the image with udi causes the job to appear as active, but pool/node/start time/end time stay frozen as n/a in overview.

**Comment by alfpark** [comment]
@nick-phillips Does the logger debug message starting with `waiting for update docker images task` show up when running `pool udi`?

Any chance that you were resizing the pool at the same time as issuing the `pool udi` command?

**Comment by alfpark** [comment]
Closing, please re-open if you are still facing this issue.
