### ISSUE TITLE
Broken pipes in Blobxfer / requests when outputting from many nodes concurrently

### ISSUE THREAD

**Issue by lediur** [Azure/batch-shipyard#48]
When I'm running a large parallel job with hundreds of simultaneous tasks, I'm running into an issue with blobxfer and requests failing to output data to blob storage.

I originally started the parallel job with 10 nodes, 7 tasks per node, for a total of 70 simultaneous tasks, and my tasks were completing correctly and uploading their results to blob storage as expected. Since each job is independent and I wanted to speed this job up, I then used `pool resize` to scale up the pool from 10 nodes to 50 nodes.

After the resize was complete, all of the jobs started failing in the output step when blobxfer is attempting to upload each task's result to blob storage. The error reports multiple broken pipes (assuming each one is a retry attempt) in `requests`. Unfortunately, I forgot to grab a error log before shutting down the cluster, but if it occurs again I'll post it here.

I'm assuming this is because I'm trying to shove too many simultaneous uploads into Blob storage at once? Is there an inherent limit to the number of simultaneous blob storage uploads? I wasn't able to find a good metric for this on Azure documentation.

**Comment by alfpark** [comment]
@lediur Your analysis is most likely the correct one. If you're hitting the same storage account from up to 70 tasks at once, that can be potentially `70 x 3 x number of cores per node` requests to storage all at once. You may want to specify `"blobxfer_extra_options": "--numworkers 2"` or something on the lower end. Mind sharing how big your data sizes for output are?

If you encounter this again, please post the exact blobxfer traceback, I can try to add some more custom retry handling for the specific error you are seeing from requests.

**Comment by lediur** [comment]
Hey Fred, thanks for the heads up. We'll take a look at the blobxfer options.

Our output files are on the order of 2-3GB each.

Sent from my Windows 10 phone

**Comment by alfpark** [comment]
Closing, please re-open if necessary.
