### ISSUE TITLE
Missing argument in NADM config file

### ISSUE THREAD

**Issue by lmiroslaw** [Azure/batch-shipyard#56]
I wanted to test your NAMD container with DC/OS and run a simple job. It turned out that /sw/NAMD_2.11_Linux-x86_64-TCP/apoa1/apoa1.namd.template is missing outputname parameter which prevents namd2 from running. When fixed namd2 apoa1.namd.template works.

I don't know if this is relevant but maybe others will be interested how to run a simple job within the container. Could you add one section to the documentation how to run 'a hello world' example with apoa1 molecule?

**Comment by alfpark** [comment]
@lmiroslaw These recipes are not intended to be used with DC/OS or other orchestrators. Batch Shipyard is built on top of Azure Batch.

`outputname` is automatically filled by the run script in the container.
