### ISSUE TITLE
Feature suggestion: user-configurable job "terminate when tasks are done" setting

### ISSUE THREAD

**Issue by lediur** [Azure/batch-shipyard#61]
There's a way to set this in the Azure portal, but it would be nice to be able to configure this officially in Batch Shipyard using `jobs.json`. I hacked this functionality into the tool earlier, but didn't put the hack back when new versions came out.

**Comment by alfpark** [comment]
@lediur Just to clarify are you asking for a feature similar to `multi_instance_auto_complete` ?

**Comment by lediur** [comment]
Yeah exactly – I assumed that `multi_instance_auto_complete` is only used for MPI tasks. I think what I did earlier was just force all jobs to be “TerminateJob” when tasks were complete, which was like a one line change.
