### ISSUE TITLE
udi command throws an exception on 0-node pool

### ISSUE THREAD

**Issue by thdeltei** [Azure/batch-shipyard#64]
Thanks @alfpark for adding the check on the number of nodes! However I think running udi on a pool with 0 nodes is not really an error. Ideally I think it would be preferable to have a message explaining that since there is 0 node in the pool, the next allocated node will have the latest version of the images and exit with return code 0, rather than bubbling up an exception.

**Comment by alfpark** [comment]
@thdeltei Is there a reason why the RuntimeError being thrown is not acceptable? Either way the program is going to exit; are you anticipating a zero exit code?

**Comment by thdeltei** [comment]
I am using the udi command in a deploy script and return codes are used for detecting when a piece of the deployment script failed and abort the deployment. In my case I have to ignore the result of the udi script because non-zero return code in that case might or might mean actual failure.
