### ISSUE TITLE
Safe to use pool autoscaling with Batch Shipyard?

### ISSUE THREAD

**Issue by lediur** [Azure/batch-shipyard#66]
I've been setting pool autoscaling on pools created using Batch Shipyard `pool add`, and I've been testing it out for a while now with no issues. I just wanted to confirm that Batch Shipyard is safe to use with autoscaling, and whether there are any considerations I should keep in mind? I'm not running multi-instance jobs.

**Comment by alfpark** [comment]
@lediur It is generally safe for pools which a total lifetime of under 7 days. The reason for this limitation is due to image pre-loading on to compute nodes and Azure Storage queues used for download ticketing. You can get around this limitation by specifying no docker images for global resources and allowing missing docker images to be run for tasks. This is strictly a workaround until #26 is properly implemented which is slated for the next major release, 2.7.0.

**Comment by alfpark** [comment]
Closing, please re-open if you have additional questions about this topic. 2.7.0 will be targeted after 2.6.0 final is released.

**Comment by lediur** [comment]
Hey @alfpark, I just got around to trying this out with one of our regularly scheduled jobs. I tried specifying the image as part of the task without adding it to `global_resources`, and Batch Shipyard seems to add the job and tasks just fine, but all of the tasks immediately die with error code 125.

I then tried to make `global_resources.docker_images` an empty array, and even removing `global_resources` entirely, but I didn't expect either of those to really do anything after looking at the source.

All of my stderr.txts look like:

```
Unable to find image 'myregistry-on.azurecr.io/subfolder/image:latest' locally
Pulling repository myregistry-on.azurecr.io/subfolder/image
docker: Error: image subfolder/image:latest not found.
See 'docker run --help'.
```

Am I using this wrong? I'm using 2.6.1. It would be fantastic to get this working so I don't have to worry about refreshing pools that I set to autoscale.

**Comment by alfpark** [comment]
@lediur Can you post your `config.json` and `jobs.json`?

**Comment by lediur** [comment]
My config.json

```json
{
    "batch_shipyard": {
        "storage_account_settings": "batch"
    },
    "docker_registry": {
        "private": {
            "server": "myregistry-on.azurecr.io"
        }
    },
    "global_resources": {
        "docker_images": [
            "subfolder/image",
            "subfolder/another-image",
            "subfolder/yet-another-image"
        ]
    }
}
```

and

an excerpt from my `jobs.json` (automatically generated):

```json
{
    "job_specifications": [
        {
            "id": "2016-job",
            "max_task_retries": 3,
            "environment_variables_keyvault_secret_id": "https://myvault.vault.azure.net/secrets/somesecret",
            "allow_run_on_missing_image": true,
            "tasks": [
                {
                    "id": "task-1",
                    "image": "subfolder/image",
                    "remove_container_after_exit": true,
                    "command": "stuff",
                    "max_task_retries": 3,
                    "retention_time": "2.00:00:00"
                },
                {
                    "id": "task-2",
                    "image": "subfolder/image",
                    "remove_container_after_exit": true,
                    "command": "stuff",
                    "max_task_retries": 3,
                    "retention_time": "2.00:00:00"
                }
            ]
        }
    ]
}
```

**Comment by lediur** [comment]
The `config.json` above contains all of the images necessary to make this work without throwing error 125. When I omit `subfolder/image` from the `global_resources.docker_images` property (i.e. the image specified in the tasks in `jobs.json`), or if I remove `global_resources.docker_images` completely, the tasks fail with error 125.

**Comment by alfpark** [comment]
@lediur Can you checkout to `develop` do a `git pull` and try again?

**Comment by lediur** [comment]
Thanks for the heads up - we normally use the CLI Docker image so I'll have to set up my shipyard dev environment again. I'll see if I can get around to that tomorrow.

**Comment by alfpark** [comment]
@lediur I've created a new docker build that follows develop for the CLI. The fixes are entirely on the submission/client side so this should suffice for testing these fixes. Please pull `alfpark/batch-shipyard:cli-develop`

**Comment by alfpark** [comment]
@lediur I've created a new docker build that follows develop for the CLI. These fixes are entirely on the submission/client side so this should suffice for testing these fixes. Please pull `alfpark/batch-shipyard:cli-develop` and give it a go.

**Comment by lediur** [comment]
Awesome. We just tested out the `cli-develop` image, and it looks like it's finding and pulling the missing Docker images from our Azure registry properly. Thanks for the quick fix!

**Comment by alfpark** [comment]
Thanks for confirming. I will roll this into 2.6.2.
