### ISSUE TITLE
Windows Server 2016 Support

### ISSUE THREAD

**Issue by alfpark** [Azure/batch-shipyard#7]
Support Windows Server 2016, specifically the `2016-Datacenter-with-Containers` sku.

- [x] Publisher/Offer/Sku allowable in convoy
- [x] Data Ingress changes
  - [x] Disallow direct ingress
  - [x] Disallow `data ingress` command to windows nodes
- [x] Disallow glusterfs
- [x] Disallow storage cluster mounts
- [x] wrap commands exit on first error
- [x] Node prep powershell script
  - [x] Follow nativedocker, skip cascade
  - [x] Download blobxfer binary
  - [x] Pull windows cargo Docker image
  - [x] Azure File Share Volume mount under pool admin user
- [x] Add RDP admin users to pool
  - [x] Password support
    - [x] Autogen support
  - [x] `pool aru`
  - [x] `pool dru`
  - [x] Do not invoke SSH path
- [x] Blobxfer support
  - [x] Blobxfer binary for Windows
  - [x] Blobxfer transfer cmd script
- [x] Cargo Docker image for Windows
  - [x] Shell scripts to cmd scripts
  - [x] Add build to AppVeyor
- [x] `data getfile`
- [x] `data getnodefile`
- [x] Jobs config
  - [x] Disallow auto-IB/GPU in jobs
  - [x] Disallow user identities
- [x] Doc updates
  - [x] Data movement guide Windows notes
  - [x] Update usage guide with new commands
  - [x] Update current limitations
  - [x] FAQ
  - [x] README (node support)
- [x] Add Windows Docker build for CLI in AppVeyor
- [x] Banner keywords

Future:
- Enable Windows Server File Share support
- Allow Samba mounts from storage clusters
- `pool listimages` support (via task)
- Credential Encryption support
- Port some recipes for Windows containers

**Comment by veonua** [comment]
example? some links to explore?
