### ISSUE TITLE
Alias of the storage account must be the same as the storage account name

### ISSUE THREAD

**Issue by lmiroslaw** [Azure/batch-shipyard#74]
I have noticed that in
https://github.com/Azure/batch-shipyard/blob/master/recipes/Caffe-GPU/config/credentials.json

the alias mystorageaccount must equal to the storage account name.

Is this a feature or a bug?

The tutorial states "The alias (or storage account link name) can be the same as the storage account name itself" (see https://github.com/Azure/batch-shipyard/blob/master/docs/11-batch-shipyard-configuration-credentials.md)

**Comment by sebastianbk** [comment]
@lmiroslaw: The alias does not need to be the same as the storage account name. I have submitted many jobs with storage account aliases different from my actual storage account names.

You just need to make sure that the alias you choose is consistently used throughout your config files.

**Comment by alfpark** [comment]
@sebastianbk is correct, the alias does not have to be the same. In fact all of the recipes are set up to not be the same, unless you somehow own the storage account named `mystorageaccount`.
