### ISSUE TITLE
Very infrequent blobxfer issues while egressing data

### ISSUE THREAD

**Issue by lediur** [Azure/batch-shipyard#81]
I just ran a data processing batch with many thousands of tasks, hundreds of jobs, and hundreds of nodes running these jobs, and ran into strange blobxfer issues three times; 

- twice, where blobxfer would fail to start entirely (no blobxfer egress log in `stdout.txt`). Both these tasks occurred on the same node. Since the node was a 2 core VM, this issue stopped this single node from processing further tasks since these two tasks essentially "livelocked" the node. The only noteworthy info from the log is that blobxfer just failed to start entirely - after the last log message from the task itself, there's nothing at all. The log just ends.

- once, where it failed to upload all of the egress files (e.g. if there's 365 files, it uploads maybe 230 of them). This one, the log does show blobxfer's startup message, computing MD5, and number of put blocks message, but there's no further information.

```
 azure blobxfer parameters [v0.12.1]
=====================================
             platform: Linux-3.10.0-514.16.1.el7.x86_64-x86_64-with
   python interpreter: CPython 3.5.2
     package versions: az.common=1.1.4 az.sml=0.20.5 az.stor=0.33.0 crypt=1.6 req=2.12.3
      subscription id: None
      management cert: None
   transfer direction: local->Azure
       local resource: .
      include pattern: ./folder/A/B/C/2010/*.json
      remote resource: None
   max num of workers: 1
              timeout: None
      storage account: mystorage
              use SAS: True
  upload as page blob: False
  auto vhd->page blob: False
 upload to file share: False
 container/share name: processed-df
  container/share URI: https://mystorage.blob.core.windows.net/mycontainer
    compute block MD5: False
     compute file MD5: True
    skip on MD5 match: False
   chunk size (bytes): 4194304
     create container: False
  keep mismatched MD5: False
     recursive if dir: True
component strip on up: 1
        remote delete: False
           collate to: disabled
      local overwrite: True
      encryption mode: disabled
         RSA key file: disabled
         RSA key type: disabled
=======================================
script start time: 2017-05-08 01:27:32

... many MD5 calculation lines ...

detected 0 empty files to upload
performing 365 put blocks/blobs and 365 put block lists
spawning 1 worker threads
```

In either case, I was able to connect to the node manually and egress the files, so the work was not lost, but I wanted to track these weird blobxfer related edge cases somewhere in case I had more info from investigating.

**Comment by alfpark** [comment]
1. I'm not sure what would be causing `blobxfer` to not even start. Are you positive the tasks completed successfully? If the task does not finish with exit code of 0, `blobxfer` will not start. You can try logging into the node and verifying if the `blobxfer` container is running. If it is, then we can try to coordinate with some deeper debugging.
2. There is no progress bar printed for `blobxfer` integrated data egress as the bar itself won't get logged in a reasonable fashion. My guess is that there was a Azure Storage hiccup and it's in a retry loop. How long did it appear "stuck" for? You can try setting a timeout, but note that if the timeout expires and `blobxfer` fails, the entire task fails.

**Comment by lediur** [comment]
1. The task completed insofar as it finished writing all of the files to the local disk. Unfortunately, I didn't check to see if blobxfer was running as a container, so I don't have any more info to post here. 

I did run into unrelated and isolated Docker issues when spinning up this many nodes (isolated to a single node which failed to start up any containers at all), so maybe it just had issues starting up the blobxfer container?

```
docker: Error response from daemon: grpc: the connection is unavailable.
time="2017-05-07T23:21:33Z" level=error msg="error getting events from daemon: context canceled" 
```

However, I didn't see anything in `stderr.txt` that would've suggested the same issue.

2. It was stuck in that state for ~6 hours (which was when I discovered it was stuck, extracted the files manually, and terminated the task). There are 365 files of about 1MB each, so it normally takes just a few minutes to egress those to blob storage. Would setting a timeout set an error code other than `1`?

**Comment by alfpark** [comment]
1. It may be related to Docker issues. Searching for this doesn't result in anything conclusive. Can you ensure that your nodes have sufficient free disk space on both disks (/dev/sdaX and /dev/sdb1)?
2. I believe it will just percolate an exception out and should exit with exit code of `1` if a timeout is specified and reached. Please be aware that timeouts in blobxfer pre-1.0.0 are blunt objects as they will apply to both the connect and read timeouts. If you encounter this again and are willing to do some debugging, you can log into the machine, docker exec into the running container, install gdb with python extensions to see where the execution is stuck.

**Comment by lediur** [comment]
Yeah, the nodes should've had free disk space, but I can confirm if I run into this issue again. I just worked around it for now since there were only 3 tasks affected and I wanted to get this processing batch done, but if this occurs again I'll comment here and try debugging through it.

**Comment by alfpark** [comment]
Closing, please re-open if you have more details to share.
