### ISSUE TITLE
Batch add tasks to a job to improve performance

### ISSUE THREAD

**Issue by rkellyxm** [Azure/batch-shipyard#86]
In the batch.py file in convoy I'm seeing that tasks are being added individually using the Batch SDK. In my case I'm creating 280+ parallel tasks, ~100 per job and it is causing my Azure Function to time out. I would suggest using batch_client.task.add_collection(job_id, task_list) instead of adding the tasks individually, or at least make it an option. Is there a reason that this would not be a desired performance enhancement?
I have attached my quick solution that I added for my shipyard installation.
 
[batch.zip](https://github.com/Azure/batch-shipyard/files/1008277/batch.zip)

**Comment by alfpark** [comment]
You're correct, this has been on the refactor target backlog. I'll target this for 2.7.0.
