### ISSUE TITLE
additional_docker_run_options being overwritten by defaults

### ISSUE THREAD

**Issue by rkellyxm** [Azure/batch-shipyard#87]
I tried to add the -w flag to "additional_docker_run_options" in the jobs config file and noticed that the settings.py file also sets that without looking to see if the flag has been specified by the user, causing my version to be ignored.

**Comment by alfpark** [comment]
The `-w` option is set by the system to set the command execution context to the proper location with regard to the job and task as it pertains to the Batch compute node.

Can you explain your scenario a little bit more in detail? I'm certainly not opposed to allowing it to be overriden.

**Comment by rkellyxm** [comment]
In my case I have a CI process incorporating the code into the image instead of copying it on task creation and would like to execute my python code using -m, which requires me to run python in the working directory
