### ISSUE TITLE
Support for Ubuntu 17.04

### ISSUE THREAD

**Issue by mkiernan** [Azure/batch-shipyard#91]
Any chance we could get 17.04 supported added ?

Thanks,
Mike

**Comment by alfpark** [comment]
Support for 17.04 needs to come from Azure Batch first. Is there a reason why you need a specific version of the host OS?

**Comment by mkiernan** [comment]
I have an application dependency on a specific version of boost, and prefer
to avoid compiling and installing a newer version onto 16.04. However, I've
found a couple of possible workarounds: 1) using an ubuntu 17.04 container
and 2) statically compiling the executable.

Please close this - I'll wait for the Azure Batch support.

**Comment by alfpark** [comment]
As Batch Shipyard provides Docker support, I'd recommend going with your first suggestion - relying on the host defeats many of the advantages of container based execution.
