### ISSUE TITLE
udi command for low priority nodes needs encryption enabled 

### ISSUE THREAD

**Issue by hieuhc** [Azure/batch-shipyard#92]
When I ran `udi` command to update docker image for a pool containing low priority nodes, it forced to update via SSH then threw an error:

`/batch-shipyard/convoy/batch.py", line 1908, in generate_docker_login_settings
cmd = cmd[1].replace(key, pw)
IndexError: list index out of range`

Probably it needs `encryption` in config.json being enabled? If so the document needs to be updated for `udi` command.

**Comment by alfpark** [comment]
This is actually a logic error in the code and does not have to do with encryption. You can use the fix immediately from the `develop` branch/CLI once the commit is pushed or wait for the next release.

**Comment by alfpark** [comment]
This issue should be fixed in develop. Credential encryption is not required for `pool udi`.

**Comment by hieuhc** [comment]
Thanks. The credential encryption issue is gone. But `pool udi` still needs ssh information to be able to run. So this is something users should be aware of when they create the pool:

`
File "/batch-shipyard/convoy/fleet.py", line 1268, in _update_docker_images
    _update_docker_images_over_ssh(batch_client, config, pool, coordcmd)
  File "/batch-shipyard/convoy/fleet.py", line 1154, in _update_docker_images_over_ssh
    ssh_private_key))
RuntimeError: SSH private key file not found at: id_rsa_shipyard
`

**Comment by alfpark** [comment]
SSH for `pool udi` is required only for low priority pools and is documented in the [current limitations doc](https://github.com/Azure/batch-shipyard/blob/master/docs/99-current-limitations.md).
