### ISSUE TITLE
if job auto_complete set to true updateable properties will disappear

### ISSUE THREAD

**Issue by rkellyxm** [Azure/batch-shipyard#97]
Based on the batch python SDK job update method comments:

>  This fully replaces all the updateable properties of the job. For
        example, if the job has constraints associated with it and if
        constraints is not specified with this request, then the Batch service
        will remove the existing constraints.

And the way auto_complete is set in the batch.py file (line 2438), all other updateable properties will be removed

`batch_client.job.update(
                job_id=job.id,
                job_update_parameter=batchmodels.JobUpdateParameter(
                    pool_info=batchmodels.PoolInformation(pool_id=pool.id),
                    on_all_tasks_complete=batchmodels.
                    OnAllTasksComplete.terminate_job))`

**Comment by alfpark** [comment]
This is now fixed in the `develop` branch (and the `cli-develop` Docker image) and will be rolled into the next release.
