### ISSUE TITLE
Update Site Extension

### ISSUE THREAD

**Issue by rkellyxm** [Azure/batch-shipyard#98]
Since you are already starting on version 2.8 would it be possible to release the 2.7 site extension? It has some very valuable fixes that I manually updated in the Kudu Tools, but an officially supported installation would be appreciated. Thanks!

**Comment by alfpark** [comment]
Currently the site extension installs from whatever is in master. I need to investigate how to automatically create nuget packages and publish them directly to the feed corresponding to each tagged release. Most likely, this will require some AppVeyor-fu.
